set(_CATKIN_CURRENT_PACKAGE "one_dof_link")
set(one_dof_link_VERSION "1.0.0")
set(one_dof_link_MAINTAINER " <12312323@qq.com>")
set(one_dof_link_PACKAGE_FORMAT "2")
set(one_dof_link_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(one_dof_link_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(one_dof_link_BUILDTOOL_DEPENDS "catkin")
set(one_dof_link_BUILDTOOL_EXPORT_DEPENDS )
set(one_dof_link_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(one_dof_link_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(one_dof_link_TEST_DEPENDS )
set(one_dof_link_DOC_DEPENDS )
set(one_dof_link_URL_WEBSITE "")
set(one_dof_link_URL_BUGTRACKER "")
set(one_dof_link_URL_REPOSITORY "")
set(one_dof_link_DEPRECATED "")