set(_CATKIN_CURRENT_PACKAGE "robots_gazebo")
set(robots_gazebo_VERSION "0.0.0")
set(robots_gazebo_MAINTAINER "luis <luis@todo.todo>")
set(robots_gazebo_PACKAGE_FORMAT "1")
set(robots_gazebo_BUILD_DEPENDS "gazebo_ros")
set(robots_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros" "gazebo_ros_control" "armc_description" "arm_hand" "xacro")
set(robots_gazebo_BUILDTOOL_DEPENDS "catkin")
set(robots_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(robots_gazebo_EXEC_DEPENDS "gazebo_ros" "gazebo_ros_control" "armc_description" "arm_hand" "xacro")
set(robots_gazebo_RUN_DEPENDS "gazebo_ros" "gazebo_ros_control" "armc_description" "arm_hand" "xacro")
set(robots_gazebo_TEST_DEPENDS )
set(robots_gazebo_DOC_DEPENDS )
set(robots_gazebo_URL_WEBSITE "http://gazebosim.org/w/index.php?title=Tutorials/1.9/Using_A_URDF_In_Gazebo")
set(robots_gazebo_URL_BUGTRACKER "https://github.com/osrf/gazebo_ros_demos/issues")
set(robots_gazebo_URL_REPOSITORY "https://github.com/osrf/gazebo_ros_demos")
set(robots_gazebo_DEPRECATED "")