set(_CATKIN_CURRENT_PACKAGE "robot_python")
set(robot_python_VERSION "0.0.0")
set(robot_python_MAINTAINER "d <d@todo.todo>")
set(robot_python_PACKAGE_FORMAT "2")
set(robot_python_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(robot_python_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_python_BUILDTOOL_DEPENDS "catkin")
set(robot_python_BUILDTOOL_EXPORT_DEPENDS )
set(robot_python_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(robot_python_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(robot_python_TEST_DEPENDS )
set(robot_python_DOC_DEPENDS )
set(robot_python_URL_WEBSITE "")
set(robot_python_URL_BUGTRACKER "")
set(robot_python_URL_REPOSITORY "")
set(robot_python_DEPRECATED "")