set(_CATKIN_CURRENT_PACKAGE "robot_kinematic")
set(robot_kinematic_VERSION "0.0.0")
set(robot_kinematic_MAINTAINER "Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(robot_kinematic_PACKAGE_FORMAT "1")
set(robot_kinematic_BUILD_DEPENDS )
set(robot_kinematic_BUILD_EXPORT_DEPENDS )
set(robot_kinematic_BUILDTOOL_DEPENDS "catkin")
set(robot_kinematic_BUILDTOOL_EXPORT_DEPENDS )
set(robot_kinematic_EXEC_DEPENDS )
set(robot_kinematic_RUN_DEPENDS )
set(robot_kinematic_TEST_DEPENDS )
set(robot_kinematic_DOC_DEPENDS )
set(robot_kinematic_URL_WEBSITE "")
set(robot_kinematic_URL_BUGTRACKER "")
set(robot_kinematic_URL_REPOSITORY "")
set(robot_kinematic_DEPRECATED "")