# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armc_form3.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArmcForm3(object):
    def setupUi(self, ArmcForm3):
        ArmcForm3.setObjectName("ArmcForm3")
        ArmcForm3.resize(1399, 895)
        self.centralwidget = QtWidgets.QWidget(ArmcForm3)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 471, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 471, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(480, 0, 521, 431))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(120, 0, 231, 31))
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setGeometry(QtCore.QRect(270, 30, 231, 371))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit_qq1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq1.setGeometry(QtCore.QRect(70, 10, 81, 41))
        self.lineEdit_qq1.setObjectName("lineEdit_qq1")
        self.button_qq1_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq1_P.setGeometry(QtCore.QRect(160, 10, 51, 41))
        self.button_qq1_P.setAutoDefault(True)
        self.button_qq1_P.setObjectName("button_qq1_P")
        self.button_qq1_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq1_N.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.button_qq1_N.setAutoDefault(True)
        self.button_qq1_N.setObjectName("button_qq1_N")
        self.lineEdit_qq2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq2.setGeometry(QtCore.QRect(70, 60, 81, 41))
        self.lineEdit_qq2.setObjectName("lineEdit_qq2")
        self.button_qq2_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq2_P.setGeometry(QtCore.QRect(160, 60, 51, 41))
        self.button_qq2_P.setAutoDefault(True)
        self.button_qq2_P.setObjectName("button_qq2_P")
        self.button_qq2_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq2_N.setGeometry(QtCore.QRect(10, 60, 51, 41))
        self.button_qq2_N.setAutoDefault(True)
        self.button_qq2_N.setObjectName("button_qq2_N")
        self.lineEdit_qq3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq3.setGeometry(QtCore.QRect(70, 110, 81, 41))
        self.lineEdit_qq3.setObjectName("lineEdit_qq3")
        self.button_qq3_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq3_P.setGeometry(QtCore.QRect(160, 110, 51, 41))
        self.button_qq3_P.setAutoDefault(True)
        self.button_qq3_P.setObjectName("button_qq3_P")
        self.button_qq3_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq3_N.setGeometry(QtCore.QRect(10, 110, 51, 41))
        self.button_qq3_N.setAutoDefault(True)
        self.button_qq3_N.setObjectName("button_qq3_N")
        self.lineEdit_qq4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq4.setGeometry(QtCore.QRect(70, 160, 81, 41))
        self.lineEdit_qq4.setObjectName("lineEdit_qq4")
        self.button_qq4_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq4_P.setGeometry(QtCore.QRect(160, 160, 51, 41))
        self.button_qq4_P.setAutoDefault(True)
        self.button_qq4_P.setObjectName("button_qq4_P")
        self.button_qq4_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq4_N.setGeometry(QtCore.QRect(10, 160, 51, 41))
        self.button_qq4_N.setAutoDefault(True)
        self.button_qq4_N.setObjectName("button_qq4_N")
        self.lineEdit_qq5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq5.setGeometry(QtCore.QRect(70, 210, 81, 41))
        self.lineEdit_qq5.setObjectName("lineEdit_qq5")
        self.button_qq5_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq5_P.setGeometry(QtCore.QRect(160, 210, 51, 41))
        self.button_qq5_P.setAutoDefault(True)
        self.button_qq5_P.setObjectName("button_qq5_P")
        self.button_qq5_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq5_N.setGeometry(QtCore.QRect(10, 210, 51, 41))
        self.button_qq5_N.setAutoDefault(True)
        self.button_qq5_N.setObjectName("button_qq5_N")
        self.lineEdit_qq6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq6.setGeometry(QtCore.QRect(70, 260, 81, 41))
        self.lineEdit_qq6.setObjectName("lineEdit_qq6")
        self.button_qq6_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq6_P.setGeometry(QtCore.QRect(160, 260, 51, 41))
        self.button_qq6_P.setAutoDefault(True)
        self.button_qq6_P.setObjectName("button_qq6_P")
        self.button_qq6_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq6_N.setGeometry(QtCore.QRect(10, 260, 51, 41))
        self.button_qq6_N.setAutoDefault(True)
        self.button_qq6_N.setObjectName("button_qq6_N")
        self.lineEdit_qq7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq7.setGeometry(QtCore.QRect(70, 310, 81, 41))
        self.lineEdit_qq7.setObjectName("lineEdit_qq7")
        self.button_qq7_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq7_P.setGeometry(QtCore.QRect(160, 310, 51, 41))
        self.button_qq7_P.setAutoDefault(True)
        self.button_qq7_P.setObjectName("button_qq7_P")
        self.button_qq7_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq7_N.setGeometry(QtCore.QRect(10, 310, 51, 41))
        self.button_qq7_N.setAutoDefault(True)
        self.button_qq7_N.setObjectName("button_qq7_N")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setGeometry(QtCore.QRect(10, 80, 241, 321))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lineEdit_xx1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx1.setGeometry(QtCore.QRect(70, 10, 81, 31))
        self.lineEdit_xx1.setObjectName("lineEdit_xx1")
        self.button_xx1_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx1_P.setGeometry(QtCore.QRect(160, 10, 51, 31))
        self.button_xx1_P.setAutoDefault(True)
        self.button_xx1_P.setObjectName("button_xx1_P")
        self.button_xx1_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx1_N.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.button_xx1_N.setAutoDefault(True)
        self.button_xx1_N.setObjectName("button_xx1_N")
        self.lineEdit_xx2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx2.setGeometry(QtCore.QRect(70, 50, 81, 31))
        self.lineEdit_xx2.setObjectName("lineEdit_xx2")
        self.button_xx2_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx2_P.setGeometry(QtCore.QRect(160, 50, 51, 31))
        self.button_xx2_P.setAutoDefault(True)
        self.button_xx2_P.setObjectName("button_xx2_P")
        self.button_xx2_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx2_N.setGeometry(QtCore.QRect(10, 50, 51, 31))
        self.button_xx2_N.setAutoDefault(True)
        self.button_xx2_N.setObjectName("button_xx2_N")
        self.lineEdit_xx3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx3.setGeometry(QtCore.QRect(70, 90, 81, 31))
        self.lineEdit_xx3.setObjectName("lineEdit_xx3")
        self.button_xx3_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx3_P.setGeometry(QtCore.QRect(160, 90, 51, 31))
        self.button_xx3_P.setAutoDefault(True)
        self.button_xx3_P.setObjectName("button_xx3_P")
        self.button_xx3_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx3_N.setGeometry(QtCore.QRect(10, 90, 51, 31))
        self.button_xx3_N.setAutoDefault(True)
        self.button_xx3_N.setObjectName("button_xx3_N")
        self.button_xx6_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx6_N.setGeometry(QtCore.QRect(10, 210, 51, 31))
        self.button_xx6_N.setAutoDefault(True)
        self.button_xx6_N.setObjectName("button_xx6_N")
        self.button_xx4_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx4_N.setGeometry(QtCore.QRect(10, 130, 51, 31))
        self.button_xx4_N.setAutoDefault(True)
        self.button_xx4_N.setObjectName("button_xx4_N")
        self.button_xx5_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx5_P.setGeometry(QtCore.QRect(160, 170, 51, 31))
        self.button_xx5_P.setAutoDefault(True)
        self.button_xx5_P.setObjectName("button_xx5_P")
        self.lineEdit_xx4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx4.setGeometry(QtCore.QRect(70, 130, 81, 31))
        self.lineEdit_xx4.setObjectName("lineEdit_xx4")
        self.button_xx4_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx4_P.setGeometry(QtCore.QRect(160, 130, 51, 31))
        self.button_xx4_P.setAutoDefault(True)
        self.button_xx4_P.setObjectName("button_xx4_P")
        self.lineEdit_xx6 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx6.setGeometry(QtCore.QRect(70, 210, 81, 31))
        self.lineEdit_xx6.setObjectName("lineEdit_xx6")
        self.button_xx5_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx5_N.setGeometry(QtCore.QRect(10, 170, 51, 31))
        self.button_xx5_N.setAutoDefault(True)
        self.button_xx5_N.setObjectName("button_xx5_N")
        self.lineEdit_xx5 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx5.setGeometry(QtCore.QRect(70, 170, 81, 31))
        self.lineEdit_xx5.setObjectName("lineEdit_xx5")
        self.button_xx6_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx6_P.setGeometry(QtCore.QRect(160, 210, 51, 31))
        self.button_xx6_P.setAutoDefault(True)
        self.button_xx6_P.setObjectName("button_xx6_P")
        self.lineEdit_xx7 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx7.setGeometry(QtCore.QRect(70, 250, 81, 41))
        self.lineEdit_xx7.setObjectName("lineEdit_xx7")
        self.button_xx7_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx7_N.setGeometry(QtCore.QRect(10, 250, 51, 41))
        self.button_xx7_N.setAutoDefault(True)
        self.button_xx7_N.setObjectName("button_xx7_N")
        self.button_xx7_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx7_P.setGeometry(QtCore.QRect(160, 250, 51, 41))
        self.button_xx7_P.setAutoDefault(True)
        self.button_xx7_P.setObjectName("button_xx7_P")
        self.label_34 = QtWidgets.QLabel(self.frame_6)
        self.label_34.setGeometry(QtCore.QRect(20, 40, 31, 31))
        self.label_34.setObjectName("label_34")
        self.lineEdit_dx = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_dx.setGeometry(QtCore.QRect(60, 40, 61, 33))
        self.lineEdit_dx.setObjectName("lineEdit_dx")
        self.lineEdit_dq = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_dq.setGeometry(QtCore.QRect(180, 40, 61, 33))
        self.lineEdit_dq.setObjectName("lineEdit_dq")
        self.label_35 = QtWidgets.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(140, 40, 31, 31))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout.addWidget(self.frame_6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(480, 430, 491, 401))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 451, 291))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 0, 111, 31))
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(80, 332, 381, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(10, 330, 71, 31))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 430, 391, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(150, 0, 111, 31))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(20, 40, 331, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 91, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 20, 91, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.button_check = QtWidgets.QPushButton(self.frame_4)
        self.button_check.setGeometry(QtCore.QRect(110, 120, 171, 61))
        self.button_check.setIconSize(QtCore.QSize(16, 16))
        self.button_check.setAutoRepeat(False)
        self.button_check.setAutoExclusive(False)
        self.button_check.setAutoRepeatDelay(400)
        self.button_check.setAutoRepeatInterval(200)
        self.button_check.setAutoDefault(True)
        self.button_check.setFlat(False)
        self.button_check.setObjectName("button_check")
        self.button_h_go = QtWidgets.QPushButton(self.frame_4)
        self.button_h_go.setGeometry(QtCore.QRect(20, 200, 91, 51))
        self.button_h_go.setAutoDefault(True)
        self.button_h_go.setObjectName("button_h_go")
        self.button_h_run = QtWidgets.QPushButton(self.frame_4)
        self.button_h_run.setGeometry(QtCore.QRect(140, 200, 91, 51))
        self.button_h_run.setAutoDefault(True)
        self.button_h_run.setObjectName("button_h_run")
        self.button_h_back = QtWidgets.QPushButton(self.frame_4)
        self.button_h_back.setGeometry(QtCore.QRect(260, 200, 91, 51))
        self.button_h_back.setAutoDefault(True)
        self.button_h_back.setObjectName("button_h_back")
        self.button_l_go = QtWidgets.QPushButton(self.frame_4)
        self.button_l_go.setGeometry(QtCore.QRect(20, 280, 91, 51))
        self.button_l_go.setAutoDefault(True)
        self.button_l_go.setObjectName("button_l_go")
        self.button_l_run = QtWidgets.QPushButton(self.frame_4)
        self.button_l_run.setGeometry(QtCore.QRect(140, 280, 91, 51))
        self.button_l_run.setAutoDefault(True)
        self.button_l_run.setObjectName("button_l_run")
        self.button_l_back = QtWidgets.QPushButton(self.frame_4)
        self.button_l_back.setGeometry(QtCore.QRect(260, 280, 91, 51))
        self.button_l_back.setAutoDefault(True)
        self.button_l_back.setObjectName("button_l_back")
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1000, 0, 361, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setGeometry(QtCore.QRect(140, 10, 201, 391))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 171, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 90, 171, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 200, 161, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_real = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_real.setObjectName("checkBox_real")
        self.verticalLayout_4.addWidget(self.checkBox_real)
        self.button_receive = QtWidgets.QPushButton(self.frame_5)
        self.button_receive.setGeometry(QtCore.QRect(20, 290, 161, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.button_read = QtWidgets.QPushButton(self.frame_8)
        self.button_read.setGeometry(QtCore.QRect(20, 330, 111, 51))
        self.button_read.setAutoDefault(True)
        self.button_read.setObjectName("button_read")
        self.button_get_init = QtWidgets.QPushButton(self.frame_8)
        self.button_get_init.setGeometry(QtCore.QRect(20, 260, 111, 51))
        self.button_get_init.setAutoDefault(True)
        self.button_get_init.setObjectName("button_get_init")
        self.button_init = QtWidgets.QPushButton(self.frame_8)
        self.button_init.setGeometry(QtCore.QRect(20, 10, 111, 51))
        self.button_init.setAutoDefault(True)
        self.button_init.setObjectName("button_init")
        self.button_inc = QtWidgets.QPushButton(self.frame_8)
        self.button_inc.setGeometry(QtCore.QRect(20, 80, 111, 51))
        self.button_inc.setCheckable(False)
        self.button_inc.setAutoDefault(True)
        self.button_inc.setObjectName("button_inc")
        self.button_home = QtWidgets.QPushButton(self.frame_8)
        self.button_home.setGeometry(QtCore.QRect(20, 160, 111, 51))
        self.button_home.setAutoDefault(True)
        self.button_home.setObjectName("button_home")
        self.verticalLayout_2.addWidget(self.frame_8)
        ArmcForm3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArmcForm3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1399, 31))
        self.menubar.setObjectName("menubar")
        ArmcForm3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArmcForm3)
        self.statusbar.setObjectName("statusbar")
        ArmcForm3.setStatusBar(self.statusbar)

        self.retranslateUi(ArmcForm3)
        QtCore.QMetaObject.connectSlotsByName(ArmcForm3)

    def retranslateUi(self, ArmcForm3):
        _translate = QtCore.QCoreApplication.translate
        ArmcForm3.setWindowTitle(_translate("ArmcForm3", "MainWindow"))
        self.label_3.setText(_translate("ArmcForm3", "增量式控制面版:长度/mm, 角度/°"))
        self.lineEdit_qq1.setText(_translate("ArmcForm3", "0"))
        self.button_qq1_P.setText(_translate("ArmcForm3", "q1++"))
        self.button_qq1_N.setText(_translate("ArmcForm3", "q1- -"))
        self.lineEdit_qq2.setText(_translate("ArmcForm3", "0"))
        self.button_qq2_P.setText(_translate("ArmcForm3", "q2++"))
        self.button_qq2_N.setText(_translate("ArmcForm3", "q2- -"))
        self.lineEdit_qq3.setText(_translate("ArmcForm3", "0"))
        self.button_qq3_P.setText(_translate("ArmcForm3", "q3++"))
        self.button_qq3_N.setText(_translate("ArmcForm3", "q3- -"))
        self.lineEdit_qq4.setText(_translate("ArmcForm3", "0"))
        self.button_qq4_P.setText(_translate("ArmcForm3", "q4++"))
        self.button_qq4_N.setText(_translate("ArmcForm3", "q4- -"))
        self.lineEdit_qq5.setText(_translate("ArmcForm3", "0"))
        self.button_qq5_P.setText(_translate("ArmcForm3", "q5++"))
        self.button_qq5_N.setText(_translate("ArmcForm3", "q5- -"))
        self.lineEdit_qq6.setText(_translate("ArmcForm3", "0"))
        self.button_qq6_P.setText(_translate("ArmcForm3", "q6++"))
        self.button_qq6_N.setText(_translate("ArmcForm3", "q6- -"))
        self.lineEdit_qq7.setText(_translate("ArmcForm3", "0"))
        self.button_qq7_P.setText(_translate("ArmcForm3", "q7++"))
        self.button_qq7_N.setText(_translate("ArmcForm3", "q7- -"))
        self.lineEdit_xx1.setText(_translate("ArmcForm3", "0"))
        self.button_xx1_P.setText(_translate("ArmcForm3", "x++"))
        self.button_xx1_N.setText(_translate("ArmcForm3", "x- -"))
        self.lineEdit_xx2.setText(_translate("ArmcForm3", "0"))
        self.button_xx2_P.setText(_translate("ArmcForm3", "y++"))
        self.button_xx2_N.setText(_translate("ArmcForm3", "y- -"))
        self.lineEdit_xx3.setText(_translate("ArmcForm3", "0"))
        self.button_xx3_P.setText(_translate("ArmcForm3", "z++"))
        self.button_xx3_N.setText(_translate("ArmcForm3", "z- -"))
        self.button_xx6_N.setText(_translate("ArmcForm3", "Y- -"))
        self.button_xx4_N.setText(_translate("ArmcForm3", "R- -"))
        self.button_xx5_P.setText(_translate("ArmcForm3", "P++"))
        self.lineEdit_xx4.setText(_translate("ArmcForm3", "0"))
        self.button_xx4_P.setText(_translate("ArmcForm3", "R++"))
        self.lineEdit_xx6.setText(_translate("ArmcForm3", "0"))
        self.button_xx5_N.setText(_translate("ArmcForm3", "P- -"))
        self.lineEdit_xx5.setText(_translate("ArmcForm3", "0"))
        self.button_xx6_P.setText(_translate("ArmcForm3", "Y++"))
        self.lineEdit_xx7.setText(_translate("ArmcForm3", "0"))
        self.button_xx7_N.setText(_translate("ArmcForm3", "Psi- -"))
        self.button_xx7_P.setText(_translate("ArmcForm3", "Psi++"))
        self.label_34.setText(_translate("ArmcForm3", "dx："))
        self.lineEdit_dx.setText(_translate("ArmcForm3", "5"))
        self.lineEdit_dq.setText(_translate("ArmcForm3", "5"))
        self.label_35.setText(_translate("ArmcForm3", "dq："))
        self.label_4.setText(_translate("ArmcForm3", "内容显示区域"))
        self.label_36.setText(_translate("ArmcForm3", "运动进度："))
        self.label.setText(_translate("ArmcForm3", "视觉引导操作区"))
        self.radioButton.setText(_translate("ArmcForm3", "门把手"))
        self.radioButton_2.setText(_translate("ArmcForm3", "密码锁"))
        self.button_check.setText(_translate("ArmcForm3", "检测"))
        self.button_h_go.setText(_translate("ArmcForm3", "h_go"))
        self.button_h_run.setText(_translate("ArmcForm3", "h_run"))
        self.button_h_back.setText(_translate("ArmcForm3", "h_back"))
        self.button_l_go.setText(_translate("ArmcForm3", "l_go"))
        self.button_l_run.setText(_translate("ArmcForm3", "l_run"))
        self.button_l_back.setText(_translate("ArmcForm3", "l_back"))
        self.button_begin.setText(_translate("ArmcForm3", "开始"))
        self.button_stop.setText(_translate("ArmcForm3", "停止"))
        self.checkBox_real.setText(_translate("ArmcForm3", "实物勾  仿真默认"))
        self.button_receive.setText(_translate("ArmcForm3", "启动节点"))
        self.button_read.setText(_translate("ArmcForm3", "读取"))
        self.button_get_init.setText(_translate("ArmcForm3", "初始位置"))
        self.button_init.setText(_translate("ArmcForm3", "起始段"))
        self.button_inc.setText(_translate("ArmcForm3", "增量控制段"))
        self.button_home.setText(_translate("ArmcForm3", "返回段"))

