# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impedance_form4.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImpForm4(object):
    def setupUi(self, ImpForm4):
        ImpForm4.setObjectName("ImpForm4")
        ImpForm4.resize(1238, 903)
        ImpForm4.setIconSize(QtCore.QSize(16, 16))
        ImpForm4.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(ImpForm4)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 421))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 471, 231))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 0, 131, 31))
        self.label.setObjectName("label")
        self.button_init = QtWidgets.QPushButton(self.frame)
        self.button_init.setGeometry(QtCore.QRect(30, 340, 111, 51))
        self.button_init.setAutoDefault(True)
        self.button_init.setObjectName("button_init")
        self.button_imp = QtWidgets.QPushButton(self.frame)
        self.button_imp.setGeometry(QtCore.QRect(190, 340, 111, 51))
        self.button_imp.setAutoDefault(True)
        self.button_imp.setObjectName("button_imp")
        self.button_end = QtWidgets.QPushButton(self.frame)
        self.button_end.setGeometry(QtCore.QRect(340, 340, 111, 51))
        self.button_end.setAutoDefault(True)
        self.button_end.setObjectName("button_end")
        self.button_receive = QtWidgets.QPushButton(self.frame)
        self.button_receive.setGeometry(QtCore.QRect(170, 270, 141, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.button_write_begin = QtWidgets.QPushButton(self.frame)
        self.button_write_begin.setGeometry(QtCore.QRect(20, 280, 121, 41))
        self.button_write_begin.setAutoDefault(True)
        self.button_write_begin.setObjectName("button_write_begin")
        self.button_write_end = QtWidgets.QPushButton(self.frame)
        self.button_write_end.setGeometry(QtCore.QRect(340, 280, 121, 41))
        self.button_write_end.setAutoDefault(True)
        self.button_write_end.setObjectName("button_write_end")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 511, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_sub_qq = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sub_qq.setGeometry(QtCore.QRect(80, 90, 381, 41))
        self.lineEdit_sub_qq.setObjectName("lineEdit_sub_qq")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 61, 33))
        self.label_17.setObjectName("label_17")
        self.lineEdit_sub_f = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sub_f.setGeometry(QtCore.QRect(80, 30, 381, 41))
        self.lineEdit_sub_f.setObjectName("lineEdit_sub_f")
        self.lineEdit_pub_qq = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_pub_qq.setGeometry(QtCore.QRect(80, 150, 381, 41))
        self.lineEdit_pub_qq.setObjectName("lineEdit_pub_qq")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(180, 0, 161, 31))
        self.label_18.setObjectName("label_18")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(10, 150, 71, 33))
        self.label_30.setObjectName("label_30")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 71, 33))
        self.label_19.setObjectName("label_19")
        self.lineEdit_data_qq = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_qq.setGeometry(QtCore.QRect(80, 200, 381, 41))
        self.lineEdit_data_qq.setObjectName("lineEdit_data_qq")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(10, 200, 71, 33))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(10, 260, 71, 33))
        self.label_32.setObjectName("label_32")
        self.lineEdit_data_f = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_f.setGeometry(QtCore.QRect(80, 260, 381, 41))
        self.lineEdit_data_f.setObjectName("lineEdit_data_f")
        self.lineEdit_path = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_path.setGeometry(QtCore.QRect(10, 320, 451, 41))
        self.lineEdit_path.setText("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(100, 0, 81, 31))
        self.label_3.setObjectName("label_3")
        self.button_read_1 = QtWidgets.QPushButton(self.frame_6)
        self.button_read_1.setGeometry(QtCore.QRect(20, 330, 91, 51))
        self.button_read_1.setAutoDefault(True)
        self.button_read_1.setObjectName("button_read_1")
        self.frame_2 = QtWidgets.QFrame(self.frame_6)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 131, 291))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_q6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q6.setGeometry(QtCore.QRect(50, 210, 61, 33))
        self.lineEdit_q6.setObjectName("lineEdit_q6")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 31, 33))
        self.label_10.setObjectName("label_10")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q3.setGeometry(QtCore.QRect(50, 90, 61, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.lineEdit_q1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q1.setGeometry(QtCore.QRect(50, 10, 61, 33))
        self.lineEdit_q1.setObjectName("lineEdit_q1")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 31, 33))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 31, 33))
        self.label_4.setObjectName("label_4")
        self.lineEdit_q2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q2.setGeometry(QtCore.QRect(50, 50, 61, 33))
        self.lineEdit_q2.setObjectName("lineEdit_q2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 31, 33))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 31, 33))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 31, 33))
        self.label_7.setObjectName("label_7")
        self.lineEdit_q4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q4.setGeometry(QtCore.QRect(50, 130, 61, 33))
        self.lineEdit_q4.setObjectName("lineEdit_q4")
        self.lineEdit_q5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q5.setGeometry(QtCore.QRect(50, 170, 61, 33))
        self.lineEdit_q5.setObjectName("lineEdit_q5")
        self.lineEdit_q7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_q7.setGeometry(QtCore.QRect(50, 250, 61, 33))
        self.lineEdit_q7.setObjectName("lineEdit_q7")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 31, 33))
        self.label_6.setObjectName("label_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(150, 30, 101, 291))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.label_12.setObjectName("label_12")
        self.lineEdit_T = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_T.setGeometry(QtCore.QRect(10, 40, 71, 33))
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 71, 31))
        self.label_14.setObjectName("label_14")
        self.lineEdit_t = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_t.setGeometry(QtCore.QRect(10, 120, 71, 33))
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.button_read_2 = QtWidgets.QPushButton(self.frame_6)
        self.button_read_2.setGeometry(QtCore.QRect(140, 330, 91, 51))
        self.button_read_2.setAutoDefault(True)
        self.button_read_2.setObjectName("button_read_2")
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 190, 191, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_armt = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_armt.setObjectName("checkBox_armt")
        self.verticalLayout_4.addWidget(self.checkBox_armt)
        self.checkBox_gazebo = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_gazebo.setObjectName("checkBox_gazebo")
        self.verticalLayout_4.addWidget(self.checkBox_gazebo)
        self.button_read_pos = QtWidgets.QPushButton(self.frame_5)
        self.button_read_pos.setGeometry(QtCore.QRect(50, 300, 161, 61))
        self.button_read_pos.setAutoDefault(True)
        self.button_read_pos.setObjectName("button_read_pos")
        self.verticalLayout_2.addWidget(self.frame_5)
        ImpForm4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImpForm4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 31))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        ImpForm4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImpForm4)
        self.statusbar.setObjectName("statusbar")
        ImpForm4.setStatusBar(self.statusbar)

        self.retranslateUi(ImpForm4)
        QtCore.QMetaObject.connectSlotsByName(ImpForm4)

    def retranslateUi(self, ImpForm4):
        _translate = QtCore.QCoreApplication.translate
        ImpForm4.setWindowTitle(_translate("ImpForm4", "MainWindow"))
        self.label.setText(_translate("ImpForm4", "运行内容显示框"))
        self.button_init.setText(_translate("ImpForm4", "起始段"))
        self.button_imp.setText(_translate("ImpForm4", "阻抗控制"))
        self.button_end.setText(_translate("ImpForm4", "返回段"))
        self.button_receive.setText(_translate("ImpForm4", "启动节点"))
        self.button_write_begin.setText(_translate("ImpForm4", "开始存储数据"))
        self.button_write_end.setText(_translate("ImpForm4", "结束存储数据"))
        self.lineEdit_sub_qq.setText(_translate("ImpForm4", "/armc/joint_states"))
        self.label_17.setText(_translate("ImpForm4", "Sub_F:"))
        self.lineEdit_sub_f.setText(_translate("ImpForm4", "/ft_sensor_topic"))
        self.lineEdit_pub_qq.setText(_translate("ImpForm4", "/armc/joint_positions_controller/command"))
        self.label_18.setText(_translate("ImpForm4", "读取数据和话题地址"))
        self.label_30.setText(_translate("ImpForm4", "Pub_qq:"))
        self.label_19.setText(_translate("ImpForm4", "Sub_qq:"))
        self.lineEdit_data_qq.setText(_translate("ImpForm4", "/home/d/catkin_ws/src/robot_python/data/impedance/armt_line_pos3.txt"))
        self.label_31.setText(_translate("ImpForm4", "data_X:"))
        self.label_32.setText(_translate("ImpForm4", "data_F:"))
        self.lineEdit_data_f.setText(_translate("ImpForm4", "/home/d/catkin_ws/src/robot_python/data/impedance/armt_line_force3.txt"))
        self.label_3.setText(_translate("ImpForm4", "初始关节角"))
        self.button_read_1.setText(_translate("ImpForm4", "初始关节"))
        self.lineEdit_q6.setText(_translate("ImpForm4", "42.5"))
        self.label_10.setText(_translate("ImpForm4", "qq1:"))
        self.lineEdit_q3.setText(_translate("ImpForm4", "0"))
        self.lineEdit_q1.setText(_translate("ImpForm4", "0"))
        self.label_9.setText(_translate("ImpForm4", "qq2:"))
        self.label_4.setText(_translate("ImpForm4", "qq4:"))
        self.lineEdit_q2.setText(_translate("ImpForm4", "46.1"))
        self.label_8.setText(_translate("ImpForm4", "qq3:"))
        self.label_5.setText(_translate("ImpForm4", "qq6:"))
        self.label_7.setText(_translate("ImpForm4", "qq5:"))
        self.lineEdit_q4.setText(_translate("ImpForm4", "91.37"))
        self.lineEdit_q5.setText(_translate("ImpForm4", "0"))
        self.lineEdit_q7.setText(_translate("ImpForm4", "0"))
        self.label_6.setText(_translate("ImpForm4", "qq7:"))
        self.label_12.setText(_translate("ImpForm4", "规划周期"))
        self.lineEdit_T.setText(_translate("ImpForm4", "0.01"))
        self.label_14.setText(_translate("ImpForm4", "规划时间"))
        self.lineEdit_t.setText(_translate("ImpForm4", "30"))
        self.button_read_2.setText(_translate("ImpForm4", "读变力"))
        self.button_begin.setText(_translate("ImpForm4", "开始"))
        self.button_stop.setText(_translate("ImpForm4", "停止"))
        self.checkBox_armt.setText(_translate("ImpForm4", "armt勾   armc默认"))
        self.checkBox_gazebo.setText(_translate("ImpForm4", "仿真勾   实物默认"))
        self.button_read_pos.setText(_translate("ImpForm4", "读取规划关节角"))

