# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windon.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 903)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 391))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_pos = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_pos.setObjectName("horizontalLayout_pos")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_vel = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_vel.setObjectName("horizontalLayout_vel")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(480, 410, 481, 421))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 461, 381))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 0, 131, 31))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(480, 10, 481, 391))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_4)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 50, 431, 241))
        self.lcdNumber.setObjectName("lcdNumber")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(10, 320, 431, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(190, 290, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(200, 10, 101, 31))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 31, 33))
        self.label_4.setObjectName("label_4")
        self.lineEdit_q5 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q5.setGeometry(QtCore.QRect(50, 210, 181, 33))
        self.lineEdit_q5.setObjectName("lineEdit_q5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 31, 33))
        self.label_5.setObjectName("label_5")
        self.lineEdit_q6 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q6.setGeometry(QtCore.QRect(50, 260, 181, 33))
        self.lineEdit_q6.setObjectName("lineEdit_q6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 31, 33))
        self.label_6.setObjectName("label_6")
        self.lineEdit_q7 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q7.setGeometry(QtCore.QRect(50, 300, 181, 33))
        self.lineEdit_q7.setObjectName("lineEdit_q7")
        self.lineEdit_q4 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q4.setGeometry(QtCore.QRect(50, 160, 180, 33))
        self.lineEdit_q4.setObjectName("lineEdit_q4")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 31, 33))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(60, 0, 151, 31))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 31, 33))
        self.label_8.setObjectName("label_8")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q3.setGeometry(QtCore.QRect(50, 120, 180, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 31, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_q2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q2.setGeometry(QtCore.QRect(50, 80, 180, 33))
        self.lineEdit_q2.setObjectName("lineEdit_q2")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 31, 33))
        self.label_10.setObjectName("label_10")
        self.lineEdit_q1 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q1.setGeometry(QtCore.QRect(50, 40, 180, 33))
        self.lineEdit_q1.setObjectName("lineEdit_q1")
        self.button_plan_begin = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_begin.setGeometry(QtCore.QRect(20, 350, 91, 41))
        self.button_plan_begin.setAutoDefault(True)
        self.button_plan_begin.setObjectName("button_plan_begin")
        self.button_plan_end = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_end.setGeometry(QtCore.QRect(130, 350, 91, 41))
        self.button_plan_end.setAutoDefault(True)
        self.button_plan_end.setObjectName("button_plan_end")
        self.lineEdit_q4.raise_()
        self.label_4.raise_()
        self.lineEdit_q5.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.lineEdit_q6.raise_()
        self.label_6.raise_()
        self.lineEdit_q7.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.lineEdit_q3.raise_()
        self.label_9.raise_()
        self.lineEdit_q2.raise_()
        self.label_10.raise_()
        self.lineEdit_q1.raise_()
        self.button_plan_begin.raise_()
        self.button_plan_end.raise_()
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 391))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.Button_begin = QtWidgets.QPushButton(self.frame_5)
        self.Button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.Button_begin.setIconSize(QtCore.QSize(16, 16))
        self.Button_begin.setAutoRepeat(False)
        self.Button_begin.setAutoExclusive(False)
        self.Button_begin.setAutoRepeatDelay(400)
        self.Button_begin.setAutoRepeatInterval(200)
        self.Button_begin.setAutoDefault(True)
        self.Button_begin.setFlat(False)
        self.Button_begin.setObjectName("Button_begin")
        self.button_end = QtWidgets.QPushButton(self.frame_5)
        self.button_end.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_end.setAutoDefault(True)
        self.button_end.setObjectName("button_end")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 200, 201, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_UR5 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_UR5.setObjectName("checkBox_UR5")
        self.verticalLayout_4.addWidget(self.checkBox_UR5)
        self.checkBox_gazebo = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_gazebo.setObjectName("checkBox_gazebo")
        self.verticalLayout_4.addWidget(self.checkBox_gazebo)
        self.button_plan = QtWidgets.QPushButton(self.frame_5)
        self.button_plan.setGeometry(QtCore.QRect(10, 300, 221, 61))
        self.button_plan.setAutoDefault(True)
        self.button_plan.setObjectName("button_plan")
        self.verticalLayout_2.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "运行内容显示框"))
        self.label_2.setText(_translate("MainWindow", "运行进度条"))
        self.label_11.setText(_translate("MainWindow", "运行时间t/s"))
        self.label_4.setText(_translate("MainWindow", "q4:"))
        self.lineEdit_q5.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "q6:"))
        self.lineEdit_q6.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "q7:"))
        self.lineEdit_q7.setText(_translate("MainWindow", "0"))
        self.lineEdit_q4.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "q5:"))
        self.label_3.setText(_translate("MainWindow", "给定关节角q/°"))
        self.label_8.setText(_translate("MainWindow", "q3:"))
        self.lineEdit_q3.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "q2:"))
        self.lineEdit_q2.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "q1:"))
        self.lineEdit_q1.setText(_translate("MainWindow", "0"))
        self.button_plan_begin.setText(_translate("MainWindow", "规划起点"))
        self.button_plan_end.setText(_translate("MainWindow", "规划终点"))
        self.Button_begin.setText(_translate("MainWindow", "开始"))
        self.button_end.setText(_translate("MainWindow", "停止"))
        self.checkBox_UR5.setText(_translate("MainWindow", "UR5勾   armc默认"))
        self.checkBox_gazebo.setText(_translate("MainWindow", "实物勾   仿真默认"))
        self.button_plan.setText(_translate("MainWindow", "规划"))

