# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_armct_form1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotArmctForm1(object):
    def setupUi(self, PlotArmctForm1):
        PlotArmctForm1.setObjectName("PlotArmctForm1")
        PlotArmctForm1.resize(1238, 903)
        PlotArmctForm1.setIconSize(QtCore.QSize(16, 16))
        PlotArmctForm1.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(PlotArmctForm1)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 431))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 431))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 461, 211))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 0, 131, 31))
        self.label.setObjectName("label")
        self.button_receive = QtWidgets.QPushButton(self.frame)
        self.button_receive.setGeometry(QtCore.QRect(130, 260, 221, 61))
        self.button_receive.setIconSize(QtCore.QSize(16, 16))
        self.button_receive.setAutoRepeat(False)
        self.button_receive.setAutoExclusive(False)
        self.button_receive.setAutoRepeatDelay(400)
        self.button_receive.setAutoRepeatInterval(200)
        self.button_receive.setAutoDefault(True)
        self.button_receive.setFlat(False)
        self.button_receive.setObjectName("button_receive")
        self.button_storage_begin = QtWidgets.QPushButton(self.frame)
        self.button_storage_begin.setGeometry(QtCore.QRect(60, 340, 101, 51))
        self.button_storage_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_storage_begin.setAutoRepeat(False)
        self.button_storage_begin.setAutoExclusive(False)
        self.button_storage_begin.setAutoRepeatDelay(400)
        self.button_storage_begin.setAutoRepeatInterval(200)
        self.button_storage_begin.setAutoDefault(True)
        self.button_storage_begin.setFlat(False)
        self.button_storage_begin.setObjectName("button_storage_begin")
        self.button_storage_end = QtWidgets.QPushButton(self.frame)
        self.button_storage_end.setGeometry(QtCore.QRect(300, 340, 101, 51))
        self.button_storage_end.setIconSize(QtCore.QSize(16, 16))
        self.button_storage_end.setAutoRepeat(False)
        self.button_storage_end.setAutoExclusive(False)
        self.button_storage_end.setAutoRepeatDelay(400)
        self.button_storage_end.setAutoRepeatInterval(200)
        self.button_storage_end.setAutoDefault(True)
        self.button_storage_end.setFlat(False)
        self.button_storage_end.setObjectName("button_storage_end")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 771, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_data_f_1 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_f_1.setGeometry(QtCore.QRect(120, 230, 611, 41))
        self.lineEdit_data_f_1.setObjectName("lineEdit_data_f_1")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(10, 230, 91, 33))
        self.label_30.setObjectName("label_30")
        self.lineEdit_data_f_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_f_2.setGeometry(QtCore.QRect(120, 310, 611, 41))
        self.lineEdit_data_f_2.setObjectName("lineEdit_data_f_2")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(10, 310, 91, 33))
        self.label_31.setObjectName("label_31")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(330, 0, 101, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_data_qq_1 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_qq_1.setGeometry(QtCore.QRect(120, 60, 611, 41))
        self.lineEdit_data_qq_1.setObjectName("lineEdit_data_qq_1")
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(10, 140, 111, 33))
        self.label_32.setObjectName("label_32")
        self.lineEdit_data_qq_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_qq_2.setGeometry(QtCore.QRect(120, 140, 611, 41))
        self.lineEdit_data_qq_2.setObjectName("lineEdit_data_qq_2")
        self.label_33 = QtWidgets.QLabel(self.frame_4)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 111, 33))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(100, 0, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 91, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_T = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_T.setGeometry(QtCore.QRect(100, 40, 121, 33))
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.button_begin = QtWidgets.QPushButton(self.frame_6)
        self.button_begin.setGeometry(QtCore.QRect(10, 100, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_6)
        self.button_stop.setGeometry(QtCore.QRect(10, 180, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 290, 191, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_real = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_real.setObjectName("checkBox_real")
        self.verticalLayout_2.addWidget(self.checkBox_real)
        self.checkBox_force = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_force.setObjectName("checkBox_force")
        self.verticalLayout_2.addWidget(self.checkBox_force)
        self.verticalLayout.addWidget(self.frame_6)
        PlotArmctForm1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotArmctForm1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 31))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        PlotArmctForm1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotArmctForm1)
        self.statusbar.setObjectName("statusbar")
        PlotArmctForm1.setStatusBar(self.statusbar)

        self.retranslateUi(PlotArmctForm1)
        QtCore.QMetaObject.connectSlotsByName(PlotArmctForm1)

    def retranslateUi(self, PlotArmctForm1):
        _translate = QtCore.QCoreApplication.translate
        PlotArmctForm1.setWindowTitle(_translate("PlotArmctForm1", "MainWindow"))
        self.label.setText(_translate("PlotArmctForm1", "运行内容显示框"))
        self.button_receive.setText(_translate("PlotArmctForm1", "接收机器人状态"))
        self.button_storage_begin.setText(_translate("PlotArmctForm1", "开始存储"))
        self.button_storage_end.setText(_translate("PlotArmctForm1", "结束存储"))
        self.lineEdit_data_f_1.setText(_translate("PlotArmctForm1", "/home/d/catkin_ws/src/robot_bag/armct/armt_force.txt"))
        self.label_30.setText(_translate("PlotArmctForm1", "armt force:"))
        self.lineEdit_data_f_2.setText(_translate("PlotArmctForm1", "/home/d/catkin_ws/src/robot_bag/armct/armc_force.txt"))
        self.label_31.setText(_translate("PlotArmctForm1", "armc force:"))
        self.label_11.setText(_translate("PlotArmctForm1", "数据存储地址"))
        self.lineEdit_data_qq_1.setText(_translate("PlotArmctForm1", "/home/d/catkin_ws/src/robot_bag/armct/armt_position.txt"))
        self.label_32.setText(_translate("PlotArmctForm1", "armc joint pos:"))
        self.lineEdit_data_qq_2.setText(_translate("PlotArmctForm1", "/home/d/catkin_ws/src/robot_bag/armct/armc_position.txt"))
        self.label_33.setText(_translate("PlotArmctForm1", "armt joint pos："))
        self.label_3.setText(_translate("PlotArmctForm1", "绘制周期"))
        self.label_9.setText(_translate("PlotArmctForm1", "接收周期："))
        self.lineEdit_T.setText(_translate("PlotArmctForm1", "0.01"))
        self.button_begin.setText(_translate("PlotArmctForm1", "开始"))
        self.button_stop.setText(_translate("PlotArmctForm1", "停止"))
        self.checkBox_real.setText(_translate("PlotArmctForm1", "实物勾      仿真默认"))
        self.checkBox_force.setText(_translate("PlotArmctForm1", "六维力勾      位置默认"))

