# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_main_windon.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotMainWindow(object):
    def setupUi(self, PlotMainWindow):
        PlotMainWindow.setObjectName("PlotMainWindow")
        PlotMainWindow.resize(1238, 903)
        PlotMainWindow.setIconSize(QtCore.QSize(16, 16))
        PlotMainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(PlotMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 431))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 431))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 461, 211))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 0, 131, 31))
        self.label.setObjectName("label")
        self.button_receive = QtWidgets.QPushButton(self.frame)
        self.button_receive.setGeometry(QtCore.QRect(130, 260, 221, 61))
        self.button_receive.setIconSize(QtCore.QSize(16, 16))
        self.button_receive.setAutoRepeat(False)
        self.button_receive.setAutoExclusive(False)
        self.button_receive.setAutoRepeatDelay(400)
        self.button_receive.setAutoRepeatInterval(200)
        self.button_receive.setAutoDefault(True)
        self.button_receive.setFlat(False)
        self.button_receive.setObjectName("button_receive")
        self.button_storage_begin = QtWidgets.QPushButton(self.frame)
        self.button_storage_begin.setGeometry(QtCore.QRect(60, 340, 101, 51))
        self.button_storage_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_storage_begin.setAutoRepeat(False)
        self.button_storage_begin.setAutoExclusive(False)
        self.button_storage_begin.setAutoRepeatDelay(400)
        self.button_storage_begin.setAutoRepeatInterval(200)
        self.button_storage_begin.setAutoDefault(True)
        self.button_storage_begin.setFlat(False)
        self.button_storage_begin.setObjectName("button_storage_begin")
        self.button_storage_end = QtWidgets.QPushButton(self.frame)
        self.button_storage_end.setGeometry(QtCore.QRect(300, 340, 101, 51))
        self.button_storage_end.setIconSize(QtCore.QSize(16, 16))
        self.button_storage_end.setAutoRepeat(False)
        self.button_storage_end.setAutoExclusive(False)
        self.button_storage_end.setAutoRepeatDelay(400)
        self.button_storage_end.setAutoRepeatInterval(200)
        self.button_storage_end.setAutoDefault(True)
        self.button_storage_end.setFlat(False)
        self.button_storage_end.setObjectName("button_storage_end")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 771, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 771, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(170, 10, 161, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_sub_f = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_sub_f.setGeometry(QtCore.QRect(80, 40, 261, 41))
        self.lineEdit_sub_f.setObjectName("lineEdit_sub_f")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 61, 33))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(370, 40, 71, 33))
        self.label_13.setObjectName("label_13")
        self.lineEdit_sub_qq = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_sub_qq.setGeometry(QtCore.QRect(440, 40, 261, 41))
        self.lineEdit_sub_qq.setObjectName("lineEdit_sub_qq")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 90, 721, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.radioButton_f1 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f1.setGeometry(QtCore.QRect(130, 20, 51, 25))
        self.radioButton_f1.setObjectName("radioButton_f1")
        self.radioButton_f2 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f2.setGeometry(QtCore.QRect(200, 20, 51, 25))
        self.radioButton_f2.setObjectName("radioButton_f2")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.label_14.setObjectName("label_14")
        self.radioButton_f5 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f5.setGeometry(QtCore.QRect(460, 20, 51, 25))
        self.radioButton_f5.setObjectName("radioButton_f5")
        self.radioButton_f3 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f3.setGeometry(QtCore.QRect(280, 20, 51, 25))
        self.radioButton_f3.setObjectName("radioButton_f3")
        self.radioButton_f4 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f4.setGeometry(QtCore.QRect(370, 20, 51, 25))
        self.radioButton_f4.setObjectName("radioButton_f4")
        self.radioButton_f6 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f6.setGeometry(QtCore.QRect(560, 20, 51, 25))
        self.radioButton_f6.setObjectName("radioButton_f6")
        self.radioButton_f = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_f.setGeometry(QtCore.QRect(640, 20, 51, 25))
        self.radioButton_f.setObjectName("radioButton_f")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 160, 721, 61))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.radioButton_q1 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q1.setGeometry(QtCore.QRect(160, 10, 51, 25))
        self.radioButton_q1.setObjectName("radioButton_q1")
        self.radioButton_q2 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q2.setGeometry(QtCore.QRect(230, 10, 51, 25))
        self.radioButton_q2.setObjectName("radioButton_q2")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.label_15.setObjectName("label_15")
        self.radioButton_q5 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q5.setGeometry(QtCore.QRect(450, 10, 51, 25))
        self.radioButton_q5.setObjectName("radioButton_q5")
        self.radioButton_q3 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q3.setGeometry(QtCore.QRect(300, 10, 51, 25))
        self.radioButton_q3.setObjectName("radioButton_q3")
        self.radioButton_q4 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q4.setGeometry(QtCore.QRect(380, 10, 51, 25))
        self.radioButton_q4.setObjectName("radioButton_q4")
        self.radioButton_q6 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q6.setGeometry(QtCore.QRect(510, 10, 51, 25))
        self.radioButton_q6.setObjectName("radioButton_q6")
        self.radioButton_q7 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_q7.setGeometry(QtCore.QRect(570, 10, 51, 25))
        self.radioButton_q7.setObjectName("radioButton_q7")
        self.radioButton_qq = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_qq.setGeometry(QtCore.QRect(640, 10, 51, 25))
        self.radioButton_qq.setObjectName("radioButton_qq")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.lineEdit_data_qq = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_qq.setGeometry(QtCore.QRect(160, 250, 561, 41))
        self.lineEdit_data_qq.setObjectName("lineEdit_data_qq")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(20, 250, 151, 33))
        self.label_30.setObjectName("label_30")
        self.lineEdit_data_f = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_f.setGeometry(QtCore.QRect(160, 310, 561, 41))
        self.lineEdit_data_f.setObjectName("lineEdit_data_f")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(10, 310, 141, 33))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(100, 0, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 91, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_T = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_T.setGeometry(QtCore.QRect(100, 40, 121, 33))
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.button_refresh = QtWidgets.QPushButton(self.frame_6)
        self.button_refresh.setGeometry(QtCore.QRect(60, 330, 131, 61))
        self.button_refresh.setAutoDefault(True)
        self.button_refresh.setObjectName("button_refresh")
        self.button_begin = QtWidgets.QPushButton(self.frame_6)
        self.button_begin.setGeometry(QtCore.QRect(10, 100, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_6)
        self.button_stop.setGeometry(QtCore.QRect(10, 210, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.verticalLayout.addWidget(self.frame_6)
        PlotMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        PlotMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotMainWindow)
        self.statusbar.setObjectName("statusbar")
        PlotMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotMainWindow)

    def retranslateUi(self, PlotMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotMainWindow.setWindowTitle(_translate("PlotMainWindow", "MainWindow"))
        self.label.setText(_translate("PlotMainWindow", "运行内容显示框"))
        self.button_receive.setText(_translate("PlotMainWindow", "接收机器人状态"))
        self.button_storage_begin.setText(_translate("PlotMainWindow", "开始存储"))
        self.button_storage_end.setText(_translate("PlotMainWindow", "结束存储"))
        self.label_11.setText(_translate("PlotMainWindow", "读取数据和话题地址"))
        self.lineEdit_sub_f.setText(_translate("PlotMainWindow", "/ft_sensor_topic"))
        self.label_12.setText(_translate("PlotMainWindow", "Sub_F:"))
        self.label_13.setText(_translate("PlotMainWindow", "Sub_qq:"))
        self.lineEdit_sub_qq.setText(_translate("PlotMainWindow", "/armc/joint_states"))
        self.radioButton_f1.setText(_translate("PlotMainWindow", "Fx"))
        self.radioButton_f2.setText(_translate("PlotMainWindow", "Fy"))
        self.label_14.setText(_translate("PlotMainWindow", "选择绘制力："))
        self.radioButton_f5.setText(_translate("PlotMainWindow", "My"))
        self.radioButton_f3.setText(_translate("PlotMainWindow", "Fz"))
        self.radioButton_f4.setText(_translate("PlotMainWindow", "Mx"))
        self.radioButton_f6.setText(_translate("PlotMainWindow", "Mz"))
        self.radioButton_f.setText(_translate("PlotMainWindow", "all"))
        self.radioButton_q1.setText(_translate("PlotMainWindow", "q1"))
        self.radioButton_q2.setText(_translate("PlotMainWindow", "q2"))
        self.label_15.setText(_translate("PlotMainWindow", "选择绘制关节角："))
        self.radioButton_q5.setText(_translate("PlotMainWindow", "q5"))
        self.radioButton_q3.setText(_translate("PlotMainWindow", "q3"))
        self.radioButton_q4.setText(_translate("PlotMainWindow", "q4"))
        self.radioButton_q6.setText(_translate("PlotMainWindow", "q6"))
        self.radioButton_q7.setText(_translate("PlotMainWindow", "q7"))
        self.radioButton_qq.setText(_translate("PlotMainWindow", "all"))
        self.lineEdit_data_qq.setText(_translate("PlotMainWindow", "/home/d/catkin_ws/src/robot_bag/joint_state/position.txt"))
        self.label_30.setText(_translate("PlotMainWindow", "关节角存储地址："))
        self.lineEdit_data_f.setText(_translate("PlotMainWindow", "/home/d/catkin_ws/src/robot_bag/force_state/force.txt"))
        self.label_31.setText(_translate("PlotMainWindow", "六维力存储地址："))
        self.label_3.setText(_translate("PlotMainWindow", "绘制周期"))
        self.label_9.setText(_translate("PlotMainWindow", "接收周期："))
        self.lineEdit_T.setText(_translate("PlotMainWindow", "0.01"))
        self.button_refresh.setText(_translate("PlotMainWindow", "刷新选择按钮"))
        self.button_begin.setText(_translate("PlotMainWindow", "开始"))
        self.button_stop.setText(_translate("PlotMainWindow", "停止"))

