# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teaching_form1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TeachingForm1(object):
    def setupUi(self, TeachingForm1):
        TeachingForm1.setObjectName("TeachingForm1")
        TeachingForm1.resize(1238, 903)
        TeachingForm1.setIconSize(QtCore.QSize(16, 16))
        TeachingForm1.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(TeachingForm1)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 431))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 411, 371))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(150, 0, 131, 31))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 551, 431))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_rbf_dir = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_rbf_dir.setGeometry(QtCore.QRect(110, 100, 411, 33))
        self.lineEdit_rbf_dir.setObjectName("lineEdit_rbf_dir")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(230, 0, 131, 31))
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.label_17.setObjectName("label_17")
        self.lineEdit_dmps_dir = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_dmps_dir.setGeometry(QtCore.QRect(110, 50, 411, 33))
        self.lineEdit_dmps_dir.setObjectName("lineEdit_dmps_dir")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.label_19.setObjectName("label_19")
        self.button_teach_learn = QtWidgets.QPushButton(self.frame)
        self.button_teach_learn.setGeometry(QtCore.QRect(50, 320, 161, 61))
        self.button_teach_learn.setAutoDefault(True)
        self.button_teach_learn.setObjectName("button_teach_learn")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.label_21.setObjectName("label_21")
        self.lineEdit_simple_data = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_simple_data.setGeometry(QtCore.QRect(110, 150, 411, 33))
        self.lineEdit_simple_data.setObjectName("lineEdit_simple_data")
        self.button_teach_rep = QtWidgets.QPushButton(self.frame)
        self.button_teach_rep.setGeometry(QtCore.QRect(310, 320, 161, 61))
        self.button_teach_rep.setAutoDefault(True)
        self.button_teach_rep.setObjectName("button_teach_rep")
        self.button_read_dir = QtWidgets.QPushButton(self.frame)
        self.button_read_dir.setGeometry(QtCore.QRect(180, 250, 161, 61))
        self.button_read_dir.setAutoDefault(True)
        self.button_read_dir.setObjectName("button_read_dir")
        self.lineEdit_general_data = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_general_data.setGeometry(QtCore.QRect(110, 200, 411, 33))
        self.lineEdit_general_data.setObjectName("lineEdit_general_data")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(10, 200, 81, 31))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 551, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(210, 0, 71, 31))
        self.label_11.setObjectName("label_11")
        self.button_ready_teach = QtWidgets.QPushButton(self.frame_4)
        self.button_ready_teach.setGeometry(QtCore.QRect(80, 240, 121, 51))
        self.button_ready_teach.setAutoDefault(True)
        self.button_ready_teach.setObjectName("button_ready_teach")
        self.button_end_teach = QtWidgets.QPushButton(self.frame_4)
        self.button_end_teach.setGeometry(QtCore.QRect(320, 240, 111, 51))
        self.button_end_teach.setAutoDefault(True)
        self.button_end_teach.setObjectName("button_end_teach")
        self.lineEdit_sub_qq = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sub_qq.setGeometry(QtCore.QRect(100, 40, 411, 33))
        self.lineEdit_sub_qq.setObjectName("lineEdit_sub_qq")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 81, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 81, 31))
        self.label_15.setObjectName("label_15")
        self.lineEdit_sub_f = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sub_f.setGeometry(QtCore.QRect(100, 90, 411, 33))
        self.lineEdit_sub_f.setObjectName("lineEdit_sub_f")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit_pub_qq = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_pub_qq.setGeometry(QtCore.QRect(100, 140, 411, 33))
        self.lineEdit_pub_qq.setObjectName("lineEdit_pub_qq")
        self.button_teach_show = QtWidgets.QPushButton(self.frame_4)
        self.button_teach_show.setGeometry(QtCore.QRect(170, 300, 191, 51))
        self.button_teach_show.setAutoDefault(True)
        self.button_teach_show.setObjectName("button_teach_show")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(10, 190, 81, 31))
        self.label_20.setObjectName("label_20")
        self.lineEdit_data_dir = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_data_dir.setGeometry(QtCore.QRect(100, 190, 411, 33))
        self.lineEdit_data_dir.setObjectName("lineEdit_data_dir")
        self.button_go_init = QtWidgets.QPushButton(self.frame_4)
        self.button_go_init.setGeometry(QtCore.QRect(30, 300, 111, 51))
        self.button_go_init.setAutoDefault(True)
        self.button_go_init.setObjectName("button_go_init")
        self.button_go_home = QtWidgets.QPushButton(self.frame_4)
        self.button_go_home.setGeometry(QtCore.QRect(390, 300, 111, 51))
        self.button_go_home.setAutoDefault(True)
        self.button_go_home.setObjectName("button_go_home")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1010, 410, 221, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 31, 33))
        self.label_4.setObjectName("label_4")
        self.lineEdit_x5 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_x5.setGeometry(QtCore.QRect(70, 170, 101, 33))
        self.lineEdit_x5.setObjectName("lineEdit_x5")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 31, 33))
        self.label_5.setObjectName("label_5")
        self.lineEdit_x6 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_x6.setGeometry(QtCore.QRect(70, 210, 101, 33))
        self.lineEdit_x6.setObjectName("lineEdit_x6")
        self.lineEdit_x4 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_x4.setGeometry(QtCore.QRect(70, 130, 101, 33))
        self.lineEdit_x4.setObjectName("lineEdit_x4")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 31, 33))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(30, 90, 31, 33))
        self.label_8.setObjectName("label_8")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q3.setGeometry(QtCore.QRect(70, 90, 101, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 31, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_x2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_x2.setGeometry(QtCore.QRect(70, 50, 101, 33))
        self.lineEdit_x2.setObjectName("lineEdit_x2")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(30, 10, 31, 33))
        self.label_10.setObjectName("label_10")
        self.lineEdit_x1 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_x1.setGeometry(QtCore.QRect(70, 10, 101, 33))
        self.lineEdit_x1.setObjectName("lineEdit_x1")
        self.button_plan_begin = QtWidgets.QPushButton(self.frame_7)
        self.button_plan_begin.setGeometry(QtCore.QRect(40, 260, 131, 51))
        self.button_plan_begin.setAutoDefault(True)
        self.button_plan_begin.setObjectName("button_plan_begin")
        self.button_plan_end = QtWidgets.QPushButton(self.frame_7)
        self.button_plan_end.setGeometry(QtCore.QRect(40, 330, 131, 51))
        self.button_plan_end.setAutoDefault(True)
        self.button_plan_end.setObjectName("button_plan_end")
        self.lineEdit_x4.raise_()
        self.label_4.raise_()
        self.lineEdit_x5.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.lineEdit_x6.raise_()
        self.label_8.raise_()
        self.lineEdit_q3.raise_()
        self.label_9.raise_()
        self.lineEdit_x2.raise_()
        self.label_10.raise_()
        self.lineEdit_x1.raise_()
        self.button_plan_begin.raise_()
        self.button_plan_end.raise_()
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1010, 10, 221, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(50, 150, 121, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(50, 280, 121, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.button_receive = QtWidgets.QPushButton(self.frame_5)
        self.button_receive.setGeometry(QtCore.QRect(30, 30, 161, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.verticalLayout_2.addWidget(self.frame_5)
        TeachingForm1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeachingForm1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        TeachingForm1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeachingForm1)
        self.statusbar.setObjectName("statusbar")
        TeachingForm1.setStatusBar(self.statusbar)

        self.retranslateUi(TeachingForm1)
        QtCore.QMetaObject.connectSlotsByName(TeachingForm1)

    def retranslateUi(self, TeachingForm1):
        _translate = QtCore.QCoreApplication.translate
        TeachingForm1.setWindowTitle(_translate("TeachingForm1", "MainWindow"))
        self.label.setText(_translate("TeachingForm1", "运行内容显示框"))
        self.lineEdit_rbf_dir.setText(_translate("TeachingForm1", "/home/d/catkin_ws/src/robot_python/data/teaching/rbf_paramter.txt"))
        self.label_12.setText(_translate("TeachingForm1", "学习与再现模块"))
        self.label_17.setText(_translate("TeachingForm1", "DMPs参数："))
        self.lineEdit_dmps_dir.setText(_translate("TeachingForm1", "/home/d/catkin_ws/src/robot_python/data/teaching/dmps_paramter.txt"))
        self.label_19.setText(_translate("TeachingForm1", "RBF参数："))
        self.button_teach_learn.setText(_translate("TeachingForm1", "学习数据"))
        self.label_21.setText(_translate("TeachingForm1", "采集数据："))
        self.lineEdit_simple_data.setText(_translate("TeachingForm1", "/home/d/catkin_ws/src/robot_python/data/teaching/teaching_data.txt"))
        self.button_teach_rep.setText(_translate("TeachingForm1", "泛化轨迹"))
        self.button_read_dir.setText(_translate("TeachingForm1", "读取数据地址"))
        self.lineEdit_general_data.setText(_translate("TeachingForm1", "/home/d/catkin_ws/src/robot_python/data/teaching/re_plan_data.txt"))
        self.label_24.setText(_translate("TeachingForm1", "泛化数据："))
        self.label_11.setText(_translate("TeachingForm1", "示教模块"))
        self.button_ready_teach.setText(_translate("TeachingForm1", "准备示教"))
        self.button_end_teach.setText(_translate("TeachingForm1", "结束示教"))
        self.lineEdit_sub_qq.setText(_translate("TeachingForm1", "/armc/joint_states"))
        self.label_14.setText(_translate("TeachingForm1", "sub_qq："))
        self.label_15.setText(_translate("TeachingForm1", "sub_f："))
        self.lineEdit_sub_f.setText(_translate("TeachingForm1", "/ft_sensor_topic"))
        self.label_16.setText(_translate("TeachingForm1", "pub_qq："))
        self.lineEdit_pub_qq.setText(_translate("TeachingForm1", "/armc/joint_positions/command"))
        self.button_teach_show.setText(_translate("TeachingForm1", "显示示教信息"))
        self.label_20.setText(_translate("TeachingForm1", "data_dir："))
        self.lineEdit_data_dir.setText(_translate("TeachingForm1", "/home/d/catkin_ws/src/robot_python/data/teaching/teaching_data.txt"))
        self.button_go_init.setText(_translate("TeachingForm1", "go_init"))
        self.button_go_home.setText(_translate("TeachingForm1", "go_home"))
        self.label_4.setText(_translate("TeachingForm1", "X4:"))
        self.lineEdit_x5.setText(_translate("TeachingForm1", "0"))
        self.label_5.setText(_translate("TeachingForm1", "X6:"))
        self.lineEdit_x6.setText(_translate("TeachingForm1", "0"))
        self.lineEdit_x4.setText(_translate("TeachingForm1", "0"))
        self.label_7.setText(_translate("TeachingForm1", "X5:"))
        self.label_8.setText(_translate("TeachingForm1", "X3:"))
        self.lineEdit_q3.setText(_translate("TeachingForm1", "0"))
        self.label_9.setText(_translate("TeachingForm1", "X2:"))
        self.lineEdit_x2.setText(_translate("TeachingForm1", "0"))
        self.label_10.setText(_translate("TeachingForm1", "X1:"))
        self.lineEdit_x1.setText(_translate("TeachingForm1", "0"))
        self.button_plan_begin.setText(_translate("TeachingForm1", "规划起点"))
        self.button_plan_end.setText(_translate("TeachingForm1", "规划终点"))
        self.button_begin.setText(_translate("TeachingForm1", "开始"))
        self.button_stop.setText(_translate("TeachingForm1", "停止"))
        self.button_receive.setText(_translate("TeachingForm1", "接收话题"))

