set(_CATKIN_CURRENT_PACKAGE "robot_msg")
set(robot_msg_VERSION "0.0.0")
set(robot_msg_MAINTAINER "d <d@todo.todo>")
set(robot_msg_PACKAGE_FORMAT "2")
set(robot_msg_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(robot_msg_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(robot_msg_BUILDTOOL_DEPENDS "catkin")
set(robot_msg_BUILDTOOL_EXPORT_DEPENDS )
set(robot_msg_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(robot_msg_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(robot_msg_TEST_DEPENDS )
set(robot_msg_DOC_DEPENDS )
set(robot_msg_URL_WEBSITE "")
set(robot_msg_URL_BUGTRACKER "")
set(robot_msg_URL_REPOSITORY "")
set(robot_msg_DEPRECATED "")