// Generated by gencpp from file armc_controller/SetArmcConfigureRequest.msg
// DO NOT EDIT!


#ifndef ARMC_CONTROLLER_MESSAGE_SETARMCCONFIGUREREQUEST_H
#define ARMC_CONTROLLER_MESSAGE_SETARMCCONFIGUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armc_controller
{
template <class ContainerAllocator>
struct SetArmcConfigureRequest_
{
  typedef SetArmcConfigureRequest_<ContainerAllocator> Type;

  SetArmcConfigureRequest_()
    : configure()  {
    }
  SetArmcConfigureRequest_(const ContainerAllocator& _alloc)
    : configure(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _configure_type;
  _configure_type configure;





  typedef boost::shared_ptr< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetArmcConfigureRequest_

typedef ::armc_controller::SetArmcConfigureRequest_<std::allocator<void> > SetArmcConfigureRequest;

typedef boost::shared_ptr< ::armc_controller::SetArmcConfigureRequest > SetArmcConfigureRequestPtr;
typedef boost::shared_ptr< ::armc_controller::SetArmcConfigureRequest const> SetArmcConfigureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace armc_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcee6d46171d1275f3230f04cb248288";
  }

  static const char* value(const ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcee6d46171d1275ULL;
  static const uint64_t static_value2 = 0xf3230f04cb248288ULL;
};

template<class ContainerAllocator>
struct DataType< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armc_controller/SetArmcConfigureRequest";
  }

  static const char* value(const ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string configure\n\
";
  }

  static const char* value(const ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.configure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetArmcConfigureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armc_controller::SetArmcConfigureRequest_<ContainerAllocator>& v)
  {
    s << indent << "configure: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.configure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMC_CONTROLLER_MESSAGE_SETARMCCONFIGUREREQUEST_H
