armc:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
      - Joint_7
 
    gains:
      Joint_1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint_2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint_3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint_4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint_5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint_6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint_7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}