arm_hand_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint1
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint2
  pid: {p: 100.0, i: 0.01, d: 100.0}

joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint3
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint4
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint5
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint6
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint7
  pid: {p: 100.0, i: 0.01, d: 10.0}
