set(_CATKIN_CURRENT_PACKAGE "ros_canopen_driver")
set(ros_canopen_driver_VERSION "0.0.0")
set(ros_canopen_driver_MAINTAINER "d <d@todo.todo>")
set(ros_canopen_driver_PACKAGE_FORMAT "2")
set(ros_canopen_driver_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "actionlib" "moveit_msgs" "message_generation" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_canopen_driver_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_canopen_driver_BUILDTOOL_DEPENDS "catkin")
set(ros_canopen_driver_BUILDTOOL_EXPORT_DEPENDS )
set(ros_canopen_driver_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "actionlib" "moveit_msgs" "message_runtime" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_canopen_driver_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "actionlib" "moveit_msgs" "message_runtime" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf" "message_generation")
set(ros_canopen_driver_TEST_DEPENDS )
set(ros_canopen_driver_DOC_DEPENDS )
set(ros_canopen_driver_URL_WEBSITE "")
set(ros_canopen_driver_URL_BUGTRACKER "")
set(ros_canopen_driver_URL_REPOSITORY "")
set(ros_canopen_driver_DEPRECATED "")