set(_CATKIN_CURRENT_PACKAGE "robot_moveit")
set(robot_moveit_VERSION "0.0.0")
set(robot_moveit_MAINTAINER "Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(robot_moveit_PACKAGE_FORMAT "1")
set(robot_moveit_BUILD_DEPENDS )
set(robot_moveit_BUILD_EXPORT_DEPENDS )
set(robot_moveit_BUILDTOOL_DEPENDS "catkin")
set(robot_moveit_BUILDTOOL_EXPORT_DEPENDS )
set(robot_moveit_EXEC_DEPENDS )
set(robot_moveit_RUN_DEPENDS )
set(robot_moveit_TEST_DEPENDS )
set(robot_moveit_DOC_DEPENDS )
set(robot_moveit_URL_WEBSITE "")
set(robot_moveit_URL_BUGTRACKER "")
set(robot_moveit_URL_REPOSITORY "")
set(robot_moveit_DEPRECATED "")