set(_CATKIN_CURRENT_PACKAGE "my_controller_pkg")
set(my_controller_pkg_VERSION "0.0.0")
set(my_controller_pkg_MAINTAINER "d <d@todo.todo>")
set(my_controller_pkg_PACKAGE_FORMAT "2")
set(my_controller_pkg_BUILD_DEPENDS "controller_interface" "hardware_interface" "pluginlib" "roscpp")
set(my_controller_pkg_BUILD_EXPORT_DEPENDS "controller_interface" "hardware_interface" "pluginlib" "roscpp")
set(my_controller_pkg_BUILDTOOL_DEPENDS "catkin")
set(my_controller_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(my_controller_pkg_EXEC_DEPENDS "controller_interface" "hardware_interface" "pluginlib" "roscpp")
set(my_controller_pkg_RUN_DEPENDS "controller_interface" "hardware_interface" "pluginlib" "roscpp")
set(my_controller_pkg_TEST_DEPENDS )
set(my_controller_pkg_DOC_DEPENDS )
set(my_controller_pkg_URL_WEBSITE "")
set(my_controller_pkg_URL_BUGTRACKER "")
set(my_controller_pkg_URL_REPOSITORY "")
set(my_controller_pkg_DEPRECATED "")