set(_CATKIN_CURRENT_PACKAGE "robot_sensor")
set(robot_sensor_VERSION "0.0.0")
set(robot_sensor_MAINTAINER "Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(robot_sensor_PACKAGE_FORMAT "1")
set(robot_sensor_BUILD_DEPENDS )
set(robot_sensor_BUILD_EXPORT_DEPENDS )
set(robot_sensor_BUILDTOOL_DEPENDS "catkin")
set(robot_sensor_BUILDTOOL_EXPORT_DEPENDS )
set(robot_sensor_EXEC_DEPENDS )
set(robot_sensor_RUN_DEPENDS )
set(robot_sensor_TEST_DEPENDS )
set(robot_sensor_DOC_DEPENDS )
set(robot_sensor_URL_WEBSITE "")
set(robot_sensor_URL_BUGTRACKER "")
set(robot_sensor_URL_REPOSITORY "")
set(robot_sensor_DEPRECATED "")