armc:
  armc_joint_publisher:
    type: "joint_state_controller/JointStateController"
    publish_rate: 100

  joint1_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint1
    pid: {p: 50.0, i: 0.1, d: 1.0}

  joint2_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint2
    pid: {p: 50.0, i: 0.1, d: 1.0}

  joint3_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint3
    pid: {p: 50.0, i: 0.1, d: 1.0}

  joint4_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint4
    pid: {p: 50.0, i: 0.1, d: 1.0}

  joint5_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint5
    pid: {p: 50.0, i: 0.1, d: 1.0}

  joint6_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint6
    pid: {p: 50.0, i: 0.1, d: 1.0}

  joint7_effort_controller:
    type: "effort_controllers/JointPositionController"
    joint: Joint7
    pid: {p: 50.0, i: 0.1, d: 1.0}

  armc_effort_controller:
    type: "armc_controller/ArmcEffortPositionController"
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
    gains:
      Joint1/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint2/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint3/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint4/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint5/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint6/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint7/pid:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  joint_group_position_controller:
    type: "effort_controllers/joint_group_position_controller"
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
    gains:
      Joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      Joint7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
