set(_CATKIN_CURRENT_PACKAGE "armt_gazebo")
set(armt_gazebo_VERSION "0.0.0")
set(armt_gazebo_MAINTAINER "luis <luis@todo.todo>")
set(armt_gazebo_PACKAGE_FORMAT "1")
set(armt_gazebo_BUILD_DEPENDS "gazebo_ros")
set(armt_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros" "gazebo_ros_control" "armt_description" "xacro")
set(armt_gazebo_BUILDTOOL_DEPENDS "catkin")
set(armt_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(armt_gazebo_EXEC_DEPENDS "gazebo_ros" "gazebo_ros_control" "armt_description" "xacro")
set(armt_gazebo_RUN_DEPENDS "gazebo_ros" "gazebo_ros_control" "armt_description" "xacro")
set(armt_gazebo_TEST_DEPENDS )
set(armt_gazebo_DOC_DEPENDS )
set(armt_gazebo_URL_WEBSITE "http://gazebosim.org/w/index.php?title=Tutorials/1.9/Using_A_URDF_In_Gazebo")
set(armt_gazebo_URL_BUGTRACKER "https://github.com/osrf/gazebo_ros_demos/issues")
set(armt_gazebo_URL_REPOSITORY "https://github.com/osrf/gazebo_ros_demos")
set(armt_gazebo_DEPRECATED "")