set(_CATKIN_CURRENT_PACKAGE "armc_moveit_config1")
set(armc_moveit_config1_VERSION "0.3.0")
set(armc_moveit_config1_MAINTAINER "cyt <qyz146006@163.com>")
set(armc_moveit_config1_PACKAGE_FORMAT "1")
set(armc_moveit_config1_BUILD_DEPENDS "armc_description")
set(armc_moveit_config1_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "armc_description")
set(armc_moveit_config1_BUILDTOOL_DEPENDS "catkin")
set(armc_moveit_config1_BUILDTOOL_EXPORT_DEPENDS )
set(armc_moveit_config1_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "armc_description")
set(armc_moveit_config1_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "armc_description")
set(armc_moveit_config1_TEST_DEPENDS )
set(armc_moveit_config1_DOC_DEPENDS )
set(armc_moveit_config1_URL_WEBSITE "http://moveit.ros.org/")
set(armc_moveit_config1_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(armc_moveit_config1_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(armc_moveit_config1_DEPRECATED "")