// Generated by gencpp from file robot_msg/SetArmcConfigureResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_SETARMCCONFIGURERESPONSE_H
#define ROBOT_MSG_MESSAGE_SETARMCCONFIGURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msg
{
template <class ContainerAllocator>
struct SetArmcConfigureResponse_
{
  typedef SetArmcConfigureResponse_<ContainerAllocator> Type;

  SetArmcConfigureResponse_()
    : result(false)  {
    }
  SetArmcConfigureResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetArmcConfigureResponse_

typedef ::robot_msg::SetArmcConfigureResponse_<std::allocator<void> > SetArmcConfigureResponse;

typedef boost::shared_ptr< ::robot_msg::SetArmcConfigureResponse > SetArmcConfigureResponsePtr;
typedef boost::shared_ptr< ::robot_msg::SetArmcConfigureResponse const> SetArmcConfigureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_msg': ['/home/d/catkin_ws/src/robot_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/SetArmcConfigureResponse";
  }

  static const char* value(const ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetArmcConfigureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::SetArmcConfigureResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_SETARMCCONFIGURERESPONSE_H
