// Generated by gencpp from file robot_msg/VisualVar.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_VISUALVAR_H
#define ROBOT_MSG_MESSAGE_VISUALVAR_H

#include <ros/service_traits.h>


#include <robot_msg/VisualVarRequest.h>
#include <robot_msg/VisualVarResponse.h>


namespace robot_msg
{

struct VisualVar
{

typedef VisualVarRequest Request;
typedef VisualVarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VisualVar
} // namespace robot_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msg::VisualVar > {
  static const char* value()
  {
    return "2cb2062d40f8dd0481d223e6c7570480";
  }

  static const char* value(const ::robot_msg::VisualVar&) { return value(); }
};

template<>
struct DataType< ::robot_msg::VisualVar > {
  static const char* value()
  {
    return "robot_msg/VisualVar";
  }

  static const char* value(const ::robot_msg::VisualVar&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msg::VisualVarRequest> should match 
// service_traits::MD5Sum< ::robot_msg::VisualVar > 
template<>
struct MD5Sum< ::robot_msg::VisualVarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::VisualVar >::value();
  }
  static const char* value(const ::robot_msg::VisualVarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::VisualVarRequest> should match 
// service_traits::DataType< ::robot_msg::VisualVar > 
template<>
struct DataType< ::robot_msg::VisualVarRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msg::VisualVar >::value();
  }
  static const char* value(const ::robot_msg::VisualVarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msg::VisualVarResponse> should match 
// service_traits::MD5Sum< ::robot_msg::VisualVar > 
template<>
struct MD5Sum< ::robot_msg::VisualVarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::VisualVar >::value();
  }
  static const char* value(const ::robot_msg::VisualVarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::VisualVarResponse> should match 
// service_traits::DataType< ::robot_msg::VisualVar > 
template<>
struct DataType< ::robot_msg::VisualVarResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msg::VisualVar >::value();
  }
  static const char* value(const ::robot_msg::VisualVarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_VISUALVAR_H
