// Generated by gencpp from file robot_msg/VisualVarResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_VISUALVARRESPONSE_H
#define ROBOT_MSG_MESSAGE_VISUALVARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msg
{
template <class ContainerAllocator>
struct VisualVarResponse_
{
  typedef VisualVarResponse_<ContainerAllocator> Type;

  VisualVarResponse_()
    : T()
    , flag(false)  {
      T.assign(0.0);
  }
  VisualVarResponse_(const ContainerAllocator& _alloc)
    : T()
    , flag(false)  {
  (void)_alloc;
      T.assign(0.0);
  }



   typedef boost::array<double, 12>  _T_type;
  _T_type T;

   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::robot_msg::VisualVarResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::VisualVarResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VisualVarResponse_

typedef ::robot_msg::VisualVarResponse_<std::allocator<void> > VisualVarResponse;

typedef boost::shared_ptr< ::robot_msg::VisualVarResponse > VisualVarResponsePtr;
typedef boost::shared_ptr< ::robot_msg::VisualVarResponse const> VisualVarResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::VisualVarResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::VisualVarResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_msg': ['/home/d/catkin_ws/src/robot_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::VisualVarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::VisualVarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::VisualVarResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fb2e4bd2f42b388bcb63e6233738cc9";
  }

  static const char* value(const ::robot_msg::VisualVarResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fb2e4bd2f42b388ULL;
  static const uint64_t static_value2 = 0xbcb63e6233738cc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/VisualVarResponse";
  }

  static const char* value(const ::robot_msg::VisualVarResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[12] T\n\
bool flag\n\
\n\
";
  }

  static const char* value(const ::robot_msg::VisualVarResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.T);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualVarResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::VisualVarResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::VisualVarResponse_<ContainerAllocator>& v)
  {
    s << indent << "T[]" << std::endl;
    for (size_t i = 0; i < v.T.size(); ++i)
    {
      s << indent << "  T[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.T[i]);
    }
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_VISUALVARRESPONSE_H
