armt_position_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7

  gains:
    joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    joint7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100  

