ur5_position_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  gains:
    shoulder_pan_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    shoulder_lift_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    elbow_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_1_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_2_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_3_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

finger_controller:
    type: "effort_controllers/JointEffortController"
    joint: finger_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}  

