# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armct_form2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArmctForm2(object):
    def setupUi(self, ArmctForm2):
        ArmctForm2.setObjectName("ArmctForm2")
        ArmctForm2.resize(1238, 903)
        ArmctForm2.setIconSize(QtCore.QSize(16, 16))
        ArmctForm2.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(ArmctForm2)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 421))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 471, 221))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 0, 131, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(70, 270, 411, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 270, 51, 31))
        self.label_15.setObjectName("label_15")
        self.button_refresh = QtWidgets.QPushButton(self.frame)
        self.button_refresh.setGeometry(QtCore.QRect(280, 320, 161, 61))
        self.button_refresh.setAutoDefault(True)
        self.button_refresh.setObjectName("button_refresh")
        self.button_read = QtWidgets.QPushButton(self.frame)
        self.button_read.setGeometry(QtCore.QRect(60, 320, 161, 61))
        self.button_read.setAutoDefault(True)
        self.button_read.setObjectName("button_read")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 511, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(10, 100, 469, 91))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(120, 0, 231, 31))
        self.label_19.setObjectName("label_19")
        self.radioButton_robot1_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_robot1_2.setGeometry(QtCore.QRect(100, 40, 91, 25))
        self.radioButton_robot1_2.setObjectName("radioButton_robot1_2")
        self.radioButton_robot2_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_robot2_2.setGeometry(QtCore.QRect(280, 40, 91, 25))
        self.radioButton_robot2_2.setObjectName("radioButton_robot2_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 469, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(160, 0, 151, 31))
        self.label_18.setObjectName("label_18")
        self.radioButton_robot1 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot1.setGeometry(QtCore.QRect(40, 40, 91, 25))
        self.radioButton_robot1.setObjectName("radioButton_robot1")
        self.radioButton_robot2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot2.setGeometry(QtCore.QRect(190, 40, 91, 25))
        self.radioButton_robot2.setObjectName("radioButton_robot2")
        self.radioButton_all = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_all.setGeometry(QtCore.QRect(320, 40, 91, 25))
        self.radioButton_all.setObjectName("radioButton_all")
        self.lineEdit_qq_armt = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_qq_armt.setGeometry(QtCore.QRect(80, 200, 401, 41))
        self.lineEdit_qq_armt.setObjectName("lineEdit_qq_armt")
        self.lineEdit_path = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_path.setGeometry(QtCore.QRect(10, 320, 471, 41))
        self.lineEdit_path.setText("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(10, 260, 71, 33))
        self.label_32.setObjectName("label_32")
        self.lineEdit_qq_armc = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_qq_armc.setGeometry(QtCore.QRect(80, 260, 401, 41))
        self.lineEdit_qq_armc.setObjectName("lineEdit_qq_armc")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(10, 200, 71, 33))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label_3.setObjectName("label_3")
        self.button_plan_init = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_init.setGeometry(QtCore.QRect(20, 60, 211, 61))
        self.button_plan_init.setAutoDefault(True)
        self.button_plan_init.setObjectName("button_plan_init")
        self.button_plan_data = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_data.setGeometry(QtCore.QRect(20, 180, 211, 61))
        self.button_plan_data.setAutoDefault(True)
        self.button_plan_data.setObjectName("button_plan_data")
        self.button_plan_home = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_home.setGeometry(QtCore.QRect(20, 300, 211, 61))
        self.button_plan_home.setAutoDefault(True)
        self.button_plan_home.setObjectName("button_plan_home")
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 190, 211, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.checkBox = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 151, 22))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.frame_8)
        self.button_receive = QtWidgets.QPushButton(self.frame_5)
        self.button_receive.setGeometry(QtCore.QRect(40, 300, 161, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.verticalLayout_2.addWidget(self.frame_5)
        ArmctForm2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArmctForm2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 31))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        ArmctForm2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArmctForm2)
        self.statusbar.setObjectName("statusbar")
        ArmctForm2.setStatusBar(self.statusbar)

        self.retranslateUi(ArmctForm2)
        QtCore.QMetaObject.connectSlotsByName(ArmctForm2)

    def retranslateUi(self, ArmctForm2):
        _translate = QtCore.QCoreApplication.translate
        ArmctForm2.setWindowTitle(_translate("ArmctForm2", "MainWindow"))
        self.label.setText(_translate("ArmctForm2", "运行内容显示框"))
        self.label_15.setText(_translate("ArmctForm2", "进度："))
        self.button_refresh.setText(_translate("ArmctForm2", "刷新选择按钮"))
        self.button_read.setText(_translate("ArmctForm2", "读取数据"))
        self.label_19.setText(_translate("ArmctForm2", "选择需要绘制状态图机械臂"))
        self.radioButton_robot1_2.setText(_translate("ArmctForm2", "armt"))
        self.radioButton_robot2_2.setText(_translate("ArmctForm2", "armc"))
        self.label_18.setText(_translate("ArmctForm2", "选择操作的机械臂"))
        self.radioButton_robot1.setText(_translate("ArmctForm2", "armt"))
        self.radioButton_robot2.setText(_translate("ArmctForm2", "armc"))
        self.radioButton_all.setText(_translate("ArmctForm2", "all"))
        self.lineEdit_qq_armt.setText(_translate("ArmctForm2", "/home/d/catkin_ws/src/robot_python/data/robots/armct/armt_postion.txt"))
        self.label_32.setText(_translate("ArmctForm2", "qq_armc:"))
        self.lineEdit_qq_armc.setText(_translate("ArmctForm2", "/home/d/catkin_ws/src/robot_python/data/robots/armct/armc_postion.txt"))
        self.label_31.setText(_translate("ArmctForm2", "qq_armt:"))
        self.label_3.setText(_translate("ArmctForm2", "规划数据并切换"))
        self.button_plan_init.setText(_translate("ArmctForm2", "起始段规划"))
        self.button_plan_data.setText(_translate("ArmctForm2", "运行数据轨迹"))
        self.button_plan_home.setText(_translate("ArmctForm2", "返回段规划"))
        self.button_begin.setText(_translate("ArmctForm2", "开始"))
        self.button_stop.setText(_translate("ArmctForm2", "停止"))
        self.checkBox.setText(_translate("ArmctForm2", "实物勾    仿真默认"))
        self.button_receive.setText(_translate("ArmctForm2", "接收机器人状态"))

