# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armc_form2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArmcForm2(object):
    def setupUi(self, ArmcForm2):
        ArmcForm2.setObjectName("ArmcForm2")
        ArmcForm2.resize(1399, 895)
        self.centralwidget = QtWidgets.QWidget(ArmcForm2)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 471, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 471, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(480, 0, 521, 431))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(120, 0, 231, 31))
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setGeometry(QtCore.QRect(270, 30, 231, 371))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit_qq1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq1.setGeometry(QtCore.QRect(70, 10, 81, 41))
        self.lineEdit_qq1.setObjectName("lineEdit_qq1")
        self.button_qq1_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq1_P.setGeometry(QtCore.QRect(160, 10, 51, 41))
        self.button_qq1_P.setAutoDefault(True)
        self.button_qq1_P.setObjectName("button_qq1_P")
        self.button_qq1_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq1_N.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.button_qq1_N.setAutoDefault(True)
        self.button_qq1_N.setObjectName("button_qq1_N")
        self.lineEdit_qq2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq2.setGeometry(QtCore.QRect(70, 60, 81, 41))
        self.lineEdit_qq2.setObjectName("lineEdit_qq2")
        self.button_qq2_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq2_P.setGeometry(QtCore.QRect(160, 60, 51, 41))
        self.button_qq2_P.setAutoDefault(True)
        self.button_qq2_P.setObjectName("button_qq2_P")
        self.button_qq2_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq2_N.setGeometry(QtCore.QRect(10, 60, 51, 41))
        self.button_qq2_N.setAutoDefault(True)
        self.button_qq2_N.setObjectName("button_qq2_N")
        self.lineEdit_qq3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq3.setGeometry(QtCore.QRect(70, 110, 81, 41))
        self.lineEdit_qq3.setObjectName("lineEdit_qq3")
        self.button_qq3_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq3_P.setGeometry(QtCore.QRect(160, 110, 51, 41))
        self.button_qq3_P.setAutoDefault(True)
        self.button_qq3_P.setObjectName("button_qq3_P")
        self.button_qq3_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq3_N.setGeometry(QtCore.QRect(10, 110, 51, 41))
        self.button_qq3_N.setAutoDefault(True)
        self.button_qq3_N.setObjectName("button_qq3_N")
        self.lineEdit_qq4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq4.setGeometry(QtCore.QRect(70, 160, 81, 41))
        self.lineEdit_qq4.setObjectName("lineEdit_qq4")
        self.button_qq4_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq4_P.setGeometry(QtCore.QRect(160, 160, 51, 41))
        self.button_qq4_P.setAutoDefault(True)
        self.button_qq4_P.setObjectName("button_qq4_P")
        self.button_qq4_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq4_N.setGeometry(QtCore.QRect(10, 160, 51, 41))
        self.button_qq4_N.setAutoDefault(True)
        self.button_qq4_N.setObjectName("button_qq4_N")
        self.lineEdit_qq5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq5.setGeometry(QtCore.QRect(70, 210, 81, 41))
        self.lineEdit_qq5.setObjectName("lineEdit_qq5")
        self.button_qq5_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq5_P.setGeometry(QtCore.QRect(160, 210, 51, 41))
        self.button_qq5_P.setAutoDefault(True)
        self.button_qq5_P.setObjectName("button_qq5_P")
        self.button_qq5_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq5_N.setGeometry(QtCore.QRect(10, 210, 51, 41))
        self.button_qq5_N.setAutoDefault(True)
        self.button_qq5_N.setObjectName("button_qq5_N")
        self.lineEdit_qq6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq6.setGeometry(QtCore.QRect(70, 260, 81, 41))
        self.lineEdit_qq6.setObjectName("lineEdit_qq6")
        self.button_qq6_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq6_P.setGeometry(QtCore.QRect(160, 260, 51, 41))
        self.button_qq6_P.setAutoDefault(True)
        self.button_qq6_P.setObjectName("button_qq6_P")
        self.button_qq6_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq6_N.setGeometry(QtCore.QRect(10, 260, 51, 41))
        self.button_qq6_N.setAutoDefault(True)
        self.button_qq6_N.setObjectName("button_qq6_N")
        self.lineEdit_qq7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_qq7.setGeometry(QtCore.QRect(70, 310, 81, 41))
        self.lineEdit_qq7.setObjectName("lineEdit_qq7")
        self.button_qq7_P = QtWidgets.QPushButton(self.frame_3)
        self.button_qq7_P.setGeometry(QtCore.QRect(160, 310, 51, 41))
        self.button_qq7_P.setAutoDefault(True)
        self.button_qq7_P.setObjectName("button_qq7_P")
        self.button_qq7_N = QtWidgets.QPushButton(self.frame_3)
        self.button_qq7_N.setGeometry(QtCore.QRect(10, 310, 51, 41))
        self.button_qq7_N.setAutoDefault(True)
        self.button_qq7_N.setObjectName("button_qq7_N")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setGeometry(QtCore.QRect(10, 80, 241, 321))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lineEdit_xx1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx1.setGeometry(QtCore.QRect(70, 10, 81, 41))
        self.lineEdit_xx1.setObjectName("lineEdit_xx1")
        self.button_xx1_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx1_P.setGeometry(QtCore.QRect(160, 10, 51, 41))
        self.button_xx1_P.setAutoDefault(True)
        self.button_xx1_P.setObjectName("button_xx1_P")
        self.button_xx1_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx1_N.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.button_xx1_N.setAutoDefault(True)
        self.button_xx1_N.setObjectName("button_xx1_N")
        self.lineEdit_xx2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx2.setGeometry(QtCore.QRect(70, 60, 81, 41))
        self.lineEdit_xx2.setObjectName("lineEdit_xx2")
        self.button_xx2_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx2_P.setGeometry(QtCore.QRect(160, 60, 51, 41))
        self.button_xx2_P.setAutoDefault(True)
        self.button_xx2_P.setObjectName("button_xx2_P")
        self.button_xx2_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx2_N.setGeometry(QtCore.QRect(10, 60, 51, 41))
        self.button_xx2_N.setAutoDefault(True)
        self.button_xx2_N.setObjectName("button_xx2_N")
        self.lineEdit_xx3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx3.setGeometry(QtCore.QRect(70, 110, 81, 41))
        self.lineEdit_xx3.setObjectName("lineEdit_xx3")
        self.button_xx3_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx3_P.setGeometry(QtCore.QRect(160, 110, 51, 41))
        self.button_xx3_P.setAutoDefault(True)
        self.button_xx3_P.setObjectName("button_xx3_P")
        self.button_xx3_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx3_N.setGeometry(QtCore.QRect(10, 110, 51, 41))
        self.button_xx3_N.setAutoDefault(True)
        self.button_xx3_N.setObjectName("button_xx3_N")
        self.button_xx6_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx6_N.setGeometry(QtCore.QRect(10, 260, 51, 41))
        self.button_xx6_N.setAutoDefault(True)
        self.button_xx6_N.setObjectName("button_xx6_N")
        self.button_xx4_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx4_N.setGeometry(QtCore.QRect(10, 160, 51, 41))
        self.button_xx4_N.setAutoDefault(True)
        self.button_xx4_N.setObjectName("button_xx4_N")
        self.button_xx5_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx5_P.setGeometry(QtCore.QRect(160, 210, 51, 41))
        self.button_xx5_P.setAutoDefault(True)
        self.button_xx5_P.setObjectName("button_xx5_P")
        self.lineEdit_xx4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx4.setGeometry(QtCore.QRect(70, 160, 81, 41))
        self.lineEdit_xx4.setObjectName("lineEdit_xx4")
        self.button_xx4_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx4_P.setGeometry(QtCore.QRect(160, 160, 51, 41))
        self.button_xx4_P.setAutoDefault(True)
        self.button_xx4_P.setObjectName("button_xx4_P")
        self.lineEdit_xx6 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx6.setGeometry(QtCore.QRect(70, 260, 81, 41))
        self.lineEdit_xx6.setObjectName("lineEdit_xx6")
        self.button_xx5_N = QtWidgets.QPushButton(self.frame_9)
        self.button_xx5_N.setGeometry(QtCore.QRect(10, 210, 51, 41))
        self.button_xx5_N.setAutoDefault(True)
        self.button_xx5_N.setObjectName("button_xx5_N")
        self.lineEdit_xx5 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_xx5.setGeometry(QtCore.QRect(70, 210, 81, 41))
        self.lineEdit_xx5.setObjectName("lineEdit_xx5")
        self.button_xx6_P = QtWidgets.QPushButton(self.frame_9)
        self.button_xx6_P.setGeometry(QtCore.QRect(160, 260, 51, 41))
        self.button_xx6_P.setAutoDefault(True)
        self.button_xx6_P.setObjectName("button_xx6_P")
        self.label_34 = QtWidgets.QLabel(self.frame_6)
        self.label_34.setGeometry(QtCore.QRect(20, 40, 31, 31))
        self.label_34.setObjectName("label_34")
        self.lineEdit_dx = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_dx.setGeometry(QtCore.QRect(60, 40, 61, 33))
        self.lineEdit_dx.setObjectName("lineEdit_dx")
        self.lineEdit_dq = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_dq.setGeometry(QtCore.QRect(180, 40, 61, 33))
        self.lineEdit_dq.setObjectName("lineEdit_dq")
        self.label_35 = QtWidgets.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(140, 40, 31, 31))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout.addWidget(self.frame_6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(480, 430, 491, 401))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 451, 291))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 0, 111, 31))
        self.label_4.setObjectName("label_4")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(80, 332, 381, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(10, 330, 71, 31))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 430, 391, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 171, 341))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_x1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x1.setGeometry(QtCore.QRect(50, 50, 101, 33))
        self.lineEdit_x1.setObjectName("lineEdit_x1")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 151, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_21.setObjectName("label_21")
        self.lineEdit_x2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x2.setGeometry(QtCore.QRect(50, 100, 101, 33))
        self.lineEdit_x2.setObjectName("lineEdit_x2")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.label_22.setObjectName("label_22")
        self.lineEdit_x3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x3.setGeometry(QtCore.QRect(50, 150, 101, 33))
        self.lineEdit_x3.setObjectName("lineEdit_x3")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(10, 250, 31, 31))
        self.label_23.setObjectName("label_23")
        self.lineEdit_x5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x5.setGeometry(QtCore.QRect(50, 250, 101, 33))
        self.lineEdit_x5.setObjectName("lineEdit_x5")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(10, 300, 31, 31))
        self.label_24.setObjectName("label_24")
        self.lineEdit_x6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x6.setGeometry(QtCore.QRect(50, 300, 101, 33))
        self.lineEdit_x6.setObjectName("lineEdit_x6")
        self.lineEdit_x4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x4.setGeometry(QtCore.QRect(50, 200, 101, 33))
        self.lineEdit_x4.setObjectName("lineEdit_x4")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.label_28.setObjectName("label_28")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(110, 0, 151, 31))
        self.label.setObjectName("label")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(210, 30, 161, 341))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 31, 33))
        self.label_11.setObjectName("label_11")
        self.lineEdit_q5 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q5.setGeometry(QtCore.QRect(50, 220, 81, 33))
        self.lineEdit_q5.setObjectName("lineEdit_q5")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 260, 31, 33))
        self.label_12.setObjectName("label_12")
        self.lineEdit_q6 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q6.setGeometry(QtCore.QRect(50, 260, 81, 33))
        self.lineEdit_q6.setObjectName("lineEdit_q6")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(10, 300, 31, 33))
        self.label_13.setObjectName("label_13")
        self.lineEdit_q7 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q7.setGeometry(QtCore.QRect(50, 300, 81, 33))
        self.lineEdit_q7.setObjectName("lineEdit_q7")
        self.lineEdit_q4 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q4.setGeometry(QtCore.QRect(50, 180, 81, 33))
        self.lineEdit_q4.setObjectName("lineEdit_q4")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(10, 220, 31, 33))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(30, 0, 111, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(10, 140, 31, 33))
        self.label_16.setObjectName("label_16")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q3.setGeometry(QtCore.QRect(50, 140, 81, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 31, 33))
        self.label_17.setObjectName("label_17")
        self.lineEdit_q2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q2.setGeometry(QtCore.QRect(50, 90, 81, 33))
        self.lineEdit_q2.setObjectName("lineEdit_q2")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 31, 33))
        self.label_18.setObjectName("label_18")
        self.lineEdit_q1 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q1.setGeometry(QtCore.QRect(50, 40, 81, 33))
        self.lineEdit_q1.setObjectName("lineEdit_q1")
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.lineEdit_q4.raise_()
        self.lineEdit_q5.raise_()
        self.lineEdit_q6.raise_()
        self.lineEdit_q7.raise_()
        self.lineEdit_q3.raise_()
        self.lineEdit_q2.raise_()
        self.lineEdit_q1.raise_()
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1000, 0, 361, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setGeometry(QtCore.QRect(140, 10, 201, 391))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 171, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 90, 171, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 180, 171, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_real = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_real.setObjectName("checkBox_real")
        self.verticalLayout_4.addWidget(self.checkBox_real)
        self.checkBox_joint = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_joint.setObjectName("checkBox_joint")
        self.verticalLayout_4.addWidget(self.checkBox_joint)
        self.button_receive = QtWidgets.QPushButton(self.frame_5)
        self.button_receive.setGeometry(QtCore.QRect(10, 310, 161, 51))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.button_get_init_qq = QtWidgets.QPushButton(self.frame_8)
        self.button_get_init_qq.setGeometry(QtCore.QRect(20, 330, 111, 51))
        self.button_get_init_qq.setAutoDefault(True)
        self.button_get_init_qq.setObjectName("button_get_init_qq")
        self.button_get_init_xx = QtWidgets.QPushButton(self.frame_8)
        self.button_get_init_xx.setGeometry(QtCore.QRect(20, 260, 111, 51))
        self.button_get_init_xx.setAutoDefault(True)
        self.button_get_init_xx.setObjectName("button_get_init_xx")
        self.button_init = QtWidgets.QPushButton(self.frame_8)
        self.button_init.setGeometry(QtCore.QRect(20, 10, 111, 51))
        self.button_init.setAutoDefault(True)
        self.button_init.setObjectName("button_init")
        self.button_inc = QtWidgets.QPushButton(self.frame_8)
        self.button_inc.setGeometry(QtCore.QRect(20, 80, 111, 51))
        self.button_inc.setCheckable(False)
        self.button_inc.setAutoDefault(True)
        self.button_inc.setObjectName("button_inc")
        self.button_home = QtWidgets.QPushButton(self.frame_8)
        self.button_home.setGeometry(QtCore.QRect(20, 160, 111, 51))
        self.button_home.setAutoDefault(True)
        self.button_home.setObjectName("button_home")
        self.verticalLayout_2.addWidget(self.frame_8)
        ArmcForm2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArmcForm2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1399, 31))
        self.menubar.setObjectName("menubar")
        ArmcForm2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArmcForm2)
        self.statusbar.setObjectName("statusbar")
        ArmcForm2.setStatusBar(self.statusbar)

        self.retranslateUi(ArmcForm2)
        QtCore.QMetaObject.connectSlotsByName(ArmcForm2)

    def retranslateUi(self, ArmcForm2):
        _translate = QtCore.QCoreApplication.translate
        ArmcForm2.setWindowTitle(_translate("ArmcForm2", "MainWindow"))
        self.label_3.setText(_translate("ArmcForm2", "增量式控制面版:长度/mm, 角度/°"))
        self.lineEdit_qq1.setText(_translate("ArmcForm2", "0"))
        self.button_qq1_P.setText(_translate("ArmcForm2", "q1++"))
        self.button_qq1_N.setText(_translate("ArmcForm2", "q1- -"))
        self.lineEdit_qq2.setText(_translate("ArmcForm2", "0"))
        self.button_qq2_P.setText(_translate("ArmcForm2", "q2++"))
        self.button_qq2_N.setText(_translate("ArmcForm2", "q2- -"))
        self.lineEdit_qq3.setText(_translate("ArmcForm2", "0"))
        self.button_qq3_P.setText(_translate("ArmcForm2", "q3++"))
        self.button_qq3_N.setText(_translate("ArmcForm2", "q3- -"))
        self.lineEdit_qq4.setText(_translate("ArmcForm2", "0"))
        self.button_qq4_P.setText(_translate("ArmcForm2", "q4++"))
        self.button_qq4_N.setText(_translate("ArmcForm2", "q4- -"))
        self.lineEdit_qq5.setText(_translate("ArmcForm2", "0"))
        self.button_qq5_P.setText(_translate("ArmcForm2", "q5++"))
        self.button_qq5_N.setText(_translate("ArmcForm2", "q5- -"))
        self.lineEdit_qq6.setText(_translate("ArmcForm2", "0"))
        self.button_qq6_P.setText(_translate("ArmcForm2", "q6++"))
        self.button_qq6_N.setText(_translate("ArmcForm2", "q6- -"))
        self.lineEdit_qq7.setText(_translate("ArmcForm2", "0"))
        self.button_qq7_P.setText(_translate("ArmcForm2", "q7++"))
        self.button_qq7_N.setText(_translate("ArmcForm2", "q7- -"))
        self.lineEdit_xx1.setText(_translate("ArmcForm2", "0"))
        self.button_xx1_P.setText(_translate("ArmcForm2", "x++"))
        self.button_xx1_N.setText(_translate("ArmcForm2", "x- -"))
        self.lineEdit_xx2.setText(_translate("ArmcForm2", "0"))
        self.button_xx2_P.setText(_translate("ArmcForm2", "y++"))
        self.button_xx2_N.setText(_translate("ArmcForm2", "y- -"))
        self.lineEdit_xx3.setText(_translate("ArmcForm2", "0"))
        self.button_xx3_P.setText(_translate("ArmcForm2", "z++"))
        self.button_xx3_N.setText(_translate("ArmcForm2", "z- -"))
        self.button_xx6_N.setText(_translate("ArmcForm2", "Y- -"))
        self.button_xx4_N.setText(_translate("ArmcForm2", "R- -"))
        self.button_xx5_P.setText(_translate("ArmcForm2", "P++"))
        self.lineEdit_xx4.setText(_translate("ArmcForm2", "0"))
        self.button_xx4_P.setText(_translate("ArmcForm2", "R++"))
        self.lineEdit_xx6.setText(_translate("ArmcForm2", "0"))
        self.button_xx5_N.setText(_translate("ArmcForm2", "P- -"))
        self.lineEdit_xx5.setText(_translate("ArmcForm2", "0"))
        self.button_xx6_P.setText(_translate("ArmcForm2", "Y++"))
        self.label_34.setText(_translate("ArmcForm2", "dx："))
        self.lineEdit_dx.setText(_translate("ArmcForm2", "5"))
        self.lineEdit_dq.setText(_translate("ArmcForm2", "5"))
        self.label_35.setText(_translate("ArmcForm2", "dq："))
        self.label_4.setText(_translate("ArmcForm2", "内容显示区域"))
        self.label_36.setText(_translate("ArmcForm2", "运动进度："))
        self.lineEdit_x1.setText(_translate("ArmcForm2", "0"))
        self.label_19.setText(_translate("ArmcForm2", "X1："))
        self.label_20.setText(_translate("ArmcForm2", "操作空间：Xd/mm"))
        self.label_21.setText(_translate("ArmcForm2", "X2："))
        self.lineEdit_x2.setText(_translate("ArmcForm2", "0"))
        self.label_22.setText(_translate("ArmcForm2", "X3："))
        self.lineEdit_x3.setText(_translate("ArmcForm2", "0"))
        self.label_23.setText(_translate("ArmcForm2", "X5："))
        self.lineEdit_x5.setText(_translate("ArmcForm2", "0"))
        self.label_24.setText(_translate("ArmcForm2", "X6："))
        self.lineEdit_x6.setText(_translate("ArmcForm2", "0"))
        self.lineEdit_x4.setText(_translate("ArmcForm2", "0"))
        self.label_28.setText(_translate("ArmcForm2", "X4："))
        self.label.setText(_translate("ArmcForm2", "操作空间输入区域"))
        self.label_11.setText(_translate("ArmcForm2", "q4:"))
        self.lineEdit_q5.setText(_translate("ArmcForm2", "0"))
        self.label_12.setText(_translate("ArmcForm2", "q6:"))
        self.lineEdit_q6.setText(_translate("ArmcForm2", "60"))
        self.label_13.setText(_translate("ArmcForm2", "q7:"))
        self.lineEdit_q7.setText(_translate("ArmcForm2", "0"))
        self.lineEdit_q4.setText(_translate("ArmcForm2", "90"))
        self.label_14.setText(_translate("ArmcForm2", "q5:"))
        self.label_15.setText(_translate("ArmcForm2", "初始关节角q/°"))
        self.label_16.setText(_translate("ArmcForm2", "q3:"))
        self.lineEdit_q3.setText(_translate("ArmcForm2", "0"))
        self.label_17.setText(_translate("ArmcForm2", "q2:"))
        self.lineEdit_q2.setText(_translate("ArmcForm2", "30"))
        self.label_18.setText(_translate("ArmcForm2", "q1:"))
        self.lineEdit_q1.setText(_translate("ArmcForm2", "0"))
        self.button_begin.setText(_translate("ArmcForm2", "开始"))
        self.button_stop.setText(_translate("ArmcForm2", "停止"))
        self.checkBox_real.setText(_translate("ArmcForm2", "实物勾  仿真默认"))
        self.checkBox_joint.setText(_translate("ArmcForm2", "关节勾  笛卡尔默认"))
        self.button_receive.setText(_translate("ArmcForm2", "启动节点"))
        self.button_get_init_qq.setText(_translate("ArmcForm2", "关节起点"))
        self.button_get_init_xx.setText(_translate("ArmcForm2", "笛卡尔起点"))
        self.button_init.setText(_translate("ArmcForm2", "起始段"))
        self.button_inc.setText(_translate("ArmcForm2", "增量控制段"))
        self.button_home.setText(_translate("ArmcForm2", "返回段"))

