# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armctr_form2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArmctrForm2(object):
    def setupUi(self, ArmctrForm2):
        ArmctrForm2.setObjectName("ArmctrForm2")
        ArmctrForm2.resize(1238, 903)
        ArmctrForm2.setIconSize(QtCore.QSize(16, 16))
        ArmctrForm2.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(ArmctrForm2)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 271))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 280, 451, 291))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 480, 511, 351))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 471, 221))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 0, 131, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(70, 270, 411, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 270, 51, 31))
        self.label_15.setObjectName("label_15")
        self.textEdit.raise_()
        self.label.raise_()
        self.progressBar.raise_()
        self.label_15.raise_()
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 511, 471))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setGeometry(QtCore.QRect(21, 40, 141, 331))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_armr_q1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_armr_q1.setGeometry(QtCore.QRect(60, 40, 61, 27))
        self.lineEdit_armr_q1.setObjectName("lineEdit_armr_q1")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_armr_q2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_armr_q2.setGeometry(QtCore.QRect(60, 80, 61, 27))
        self.lineEdit_armr_q2.setObjectName("lineEdit_armr_q2")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 41, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_armr_q3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_armr_q3.setGeometry(QtCore.QRect(60, 120, 61, 27))
        self.lineEdit_armr_q3.setObjectName("lineEdit_armr_q3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 41, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_armr_q4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_armr_q4.setGeometry(QtCore.QRect(60, 160, 61, 27))
        self.lineEdit_armr_q4.setObjectName("lineEdit_armr_q4")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 200, 41, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_armr_q5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_armr_q5.setGeometry(QtCore.QRect(60, 200, 61, 27))
        self.lineEdit_armr_q5.setObjectName("lineEdit_armr_q5")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 41, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_armr_q6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_armr_q6.setGeometry(QtCore.QRect(60, 240, 61, 27))
        self.lineEdit_armr_q6.setObjectName("lineEdit_armr_q6")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(330, 40, 151, 331))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.label_19.setObjectName("label_19")
        self.lineEdit_armc_q1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q1.setGeometry(QtCore.QRect(60, 40, 71, 27))
        self.lineEdit_armc_q1.setObjectName("lineEdit_armc_q1")
        self.lineEdit_armc_q2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q2.setGeometry(QtCore.QRect(60, 80, 71, 27))
        self.lineEdit_armc_q2.setObjectName("lineEdit_armc_q2")
        self.lineEdit_armc_q3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q3.setGeometry(QtCore.QRect(60, 120, 71, 27))
        self.lineEdit_armc_q3.setObjectName("lineEdit_armc_q3")
        self.lineEdit_armc_q4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q4.setGeometry(QtCore.QRect(60, 160, 71, 27))
        self.lineEdit_armc_q4.setObjectName("lineEdit_armc_q4")
        self.lineEdit_armc_q5 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q5.setGeometry(QtCore.QRect(60, 200, 71, 27))
        self.lineEdit_armc_q5.setObjectName("lineEdit_armc_q5")
        self.lineEdit_armc_q6 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q6.setGeometry(QtCore.QRect(60, 240, 71, 27))
        self.lineEdit_armc_q6.setObjectName("lineEdit_armc_q6")
        self.lineEdit_armc_q7 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_armc_q7.setGeometry(QtCore.QRect(60, 280, 71, 27))
        self.lineEdit_armc_q7.setObjectName("lineEdit_armc_q7")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(10, 200, 41, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        self.label_28.setGeometry(QtCore.QRect(10, 280, 41, 21))
        self.label_28.setObjectName("label_28")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 41, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        self.label_23.setGeometry(QtCore.QRect(10, 240, 41, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setGeometry(QtCore.QRect(10, 120, 41, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_9)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_25.setObjectName("label_25")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(170, 40, 151, 331))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.label_10.setObjectName("label_10")
        self.lineEdit_armt_q1 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q1.setGeometry(QtCore.QRect(60, 40, 71, 27))
        self.lineEdit_armt_q1.setObjectName("lineEdit_armt_q1")
        self.lineEdit_armt_q2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q2.setGeometry(QtCore.QRect(60, 80, 71, 27))
        self.lineEdit_armt_q2.setObjectName("lineEdit_armt_q2")
        self.lineEdit_armt_q3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q3.setGeometry(QtCore.QRect(60, 120, 71, 27))
        self.lineEdit_armt_q3.setObjectName("lineEdit_armt_q3")
        self.lineEdit_armt_q4 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q4.setGeometry(QtCore.QRect(60, 160, 71, 27))
        self.lineEdit_armt_q4.setObjectName("lineEdit_armt_q4")
        self.lineEdit_armt_q5 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q5.setGeometry(QtCore.QRect(60, 200, 71, 27))
        self.lineEdit_armt_q5.setObjectName("lineEdit_armt_q5")
        self.lineEdit_armt_q6 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q6.setGeometry(QtCore.QRect(60, 240, 71, 27))
        self.lineEdit_armt_q6.setObjectName("lineEdit_armt_q6")
        self.lineEdit_armt_q7 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_armt_q7.setGeometry(QtCore.QRect(60, 280, 71, 27))
        self.lineEdit_armt_q7.setObjectName("lineEdit_armt_q7")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 41, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 240, 41, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(10, 200, 41, 21))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(10, 120, 41, 21))
        self.label_17.setObjectName("label_17")
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setGeometry(QtCore.QRect(10, 280, 41, 21))
        self.label_27.setObjectName("label_27")
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setGeometry(QtCore.QRect(190, 10, 131, 20))
        self.label_26.setObjectName("label_26")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(20, 380, 461, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(160, 0, 151, 21))
        self.label_18.setObjectName("label_18")
        self.radioButton_armt = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_armt.setGeometry(QtCore.QRect(140, 30, 71, 25))
        self.radioButton_armt.setObjectName("radioButton_armt")
        self.radioButton_armc = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_armc.setGeometry(QtCore.QRect(250, 30, 71, 25))
        self.radioButton_armc.setObjectName("radioButton_armc")
        self.radioButton_all = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_all.setGeometry(QtCore.QRect(370, 30, 51, 25))
        self.radioButton_all.setChecked(True)
        self.radioButton_all.setObjectName("radioButton_all")
        self.radioButton_armr = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_armr.setGeometry(QtCore.QRect(20, 30, 61, 25))
        self.radioButton_armr.setObjectName("radioButton_armr")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 480, 261, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label_3.setObjectName("label_3")
        self.button_plan_home = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_home.setGeometry(QtCore.QRect(20, 160, 211, 61))
        self.button_plan_home.setAutoDefault(True)
        self.button_plan_home.setObjectName("button_plan_home")
        self.button_plan_init = QtWidgets.QPushButton(self.frame_6)
        self.button_plan_init.setGeometry(QtCore.QRect(20, 70, 211, 61))
        self.button_plan_init.setAutoDefault(True)
        self.button_plan_init.setObjectName("button_plan_init")
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 190, 221, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.checkBox_real = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_real.setGeometry(QtCore.QRect(20, 20, 161, 22))
        self.checkBox_real.setObjectName("checkBox_real")
        self.checkBox_force = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_force.setGeometry(QtCore.QRect(20, 50, 161, 21))
        self.checkBox_force.setObjectName("checkBox_force")
        self.verticalLayout_4.addWidget(self.frame_8)
        self.button_receive = QtWidgets.QPushButton(self.frame_5)
        self.button_receive.setGeometry(QtCore.QRect(50, 360, 161, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 570, 451, 261))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        ArmctrForm2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArmctrForm2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 31))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        ArmctrForm2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArmctrForm2)
        self.statusbar.setObjectName("statusbar")
        ArmctrForm2.setStatusBar(self.statusbar)

        self.retranslateUi(ArmctrForm2)
        QtCore.QMetaObject.connectSlotsByName(ArmctrForm2)

    def retranslateUi(self, ArmctrForm2):
        _translate = QtCore.QCoreApplication.translate
        ArmctrForm2.setWindowTitle(_translate("ArmctrForm2", "MainWindow"))
        self.label.setText(_translate("ArmctrForm2", "运行内容显示框"))
        self.label_15.setText(_translate("ArmctrForm2", "进度："))
        self.label_2.setText(_translate("ArmctrForm2", "UR5"))
        self.label_4.setText(_translate("ArmctrForm2", "关节1:"))
        self.lineEdit_armr_q1.setText(_translate("ArmctrForm2", "0"))
        self.label_5.setText(_translate("ArmctrForm2", "关节2:"))
        self.lineEdit_armr_q2.setText(_translate("ArmctrForm2", "0"))
        self.label_6.setText(_translate("ArmctrForm2", "关节3:"))
        self.lineEdit_armr_q3.setText(_translate("ArmctrForm2", "0"))
        self.label_7.setText(_translate("ArmctrForm2", "关节4:"))
        self.lineEdit_armr_q4.setText(_translate("ArmctrForm2", "0"))
        self.label_8.setText(_translate("ArmctrForm2", "关节5:"))
        self.lineEdit_armr_q5.setText(_translate("ArmctrForm2", "0"))
        self.label_9.setText(_translate("ArmctrForm2", "关节6:"))
        self.lineEdit_armr_q6.setText(_translate("ArmctrForm2", "0"))
        self.label_19.setText(_translate("ArmctrForm2", "Armc"))
        self.lineEdit_armc_q1.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armc_q2.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armc_q3.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armc_q4.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armc_q5.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armc_q6.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armc_q7.setText(_translate("ArmctrForm2", "0"))
        self.label_20.setText(_translate("ArmctrForm2", "关节5:"))
        self.label_21.setText(_translate("ArmctrForm2", "关节2:"))
        self.label_28.setText(_translate("ArmctrForm2", "关节7:"))
        self.label_22.setText(_translate("ArmctrForm2", "关节4:"))
        self.label_23.setText(_translate("ArmctrForm2", "关节6:"))
        self.label_24.setText(_translate("ArmctrForm2", "关节3:"))
        self.label_25.setText(_translate("ArmctrForm2", "关节1:"))
        self.label_10.setText(_translate("ArmctrForm2", "Armt"))
        self.lineEdit_armt_q1.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armt_q2.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armt_q3.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armt_q4.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armt_q5.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armt_q6.setText(_translate("ArmctrForm2", "0"))
        self.lineEdit_armt_q7.setText(_translate("ArmctrForm2", "0"))
        self.label_11.setText(_translate("ArmctrForm2", "关节4:"))
        self.label_12.setText(_translate("ArmctrForm2", "关节6:"))
        self.label_13.setText(_translate("ArmctrForm2", "关节1:"))
        self.label_14.setText(_translate("ArmctrForm2", "关节5:"))
        self.label_16.setText(_translate("ArmctrForm2", "关节2:"))
        self.label_17.setText(_translate("ArmctrForm2", "关节3:"))
        self.label_27.setText(_translate("ArmctrForm2", "关节7:"))
        self.label_26.setText(_translate("ArmctrForm2", "读取目标关节角度"))
        self.label_18.setText(_translate("ArmctrForm2", "选择操作的机械臂"))
        self.radioButton_armt.setText(_translate("ArmctrForm2", "armt"))
        self.radioButton_armc.setText(_translate("ArmctrForm2", "armc"))
        self.radioButton_all.setText(_translate("ArmctrForm2", "all"))
        self.radioButton_armr.setText(_translate("ArmctrForm2", "armr"))
        self.label_3.setText(_translate("ArmctrForm2", "规划数据并切换"))
        self.button_plan_home.setText(_translate("ArmctrForm2", "返回段规划"))
        self.button_plan_init.setText(_translate("ArmctrForm2", "起始段规划"))
        self.button_begin.setText(_translate("ArmctrForm2", "开始"))
        self.button_stop.setText(_translate("ArmctrForm2", "停止"))
        self.checkBox_real.setText(_translate("ArmctrForm2", "实物勾    仿真默认"))
        self.checkBox_force.setText(_translate("ArmctrForm2", "六维力勾    位置默认"))
        self.button_receive.setText(_translate("ArmctrForm2", "接收机器人状态"))

