# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impedance_form1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1399, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 471, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 471, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(480, 0, 491, 431))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 71, 33))
        self.label_8.setObjectName("label_8")
        self.lineEdit_sub_qq = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_sub_qq.setGeometry(QtCore.QRect(80, 90, 381, 41))
        self.lineEdit_sub_qq.setObjectName("lineEdit_sub_qq")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 61, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_sub_f = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_sub_f.setGeometry(QtCore.QRect(80, 30, 381, 41))
        self.lineEdit_sub_f.setObjectName("lineEdit_sub_f")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(170, 0, 161, 31))
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setGeometry(QtCore.QRect(0, 200, 491, 231))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(160, 0, 171, 31))
        self.label_2.setObjectName("label_2")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 21, 33))
        self.label_25.setObjectName("label_25")
        self.lineEdit_m1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_m1.setGeometry(QtCore.QRect(40, 40, 61, 33))
        self.lineEdit_m1.setObjectName("lineEdit_m1")
        self.lineEdit_m6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_m6.setGeometry(QtCore.QRect(390, 40, 61, 33))
        self.lineEdit_m6.setObjectName("lineEdit_m6")
        self.lineEdit_m5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_m5.setGeometry(QtCore.QRect(320, 40, 61, 33))
        self.lineEdit_m5.setObjectName("lineEdit_m5")
        self.lineEdit_m4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_m4.setGeometry(QtCore.QRect(250, 40, 61, 33))
        self.lineEdit_m4.setObjectName("lineEdit_m4")
        self.lineEdit_m3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_m3.setGeometry(QtCore.QRect(180, 40, 61, 33))
        self.lineEdit_m3.setObjectName("lineEdit_m3")
        self.lineEdit_m2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_m2.setGeometry(QtCore.QRect(110, 40, 61, 33))
        self.lineEdit_m2.setObjectName("lineEdit_m2")
        self.lineEdit_b3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b3.setGeometry(QtCore.QRect(180, 80, 61, 33))
        self.lineEdit_b3.setObjectName("lineEdit_b3")
        self.lineEdit_b5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b5.setGeometry(QtCore.QRect(320, 80, 61, 33))
        self.lineEdit_b5.setObjectName("lineEdit_b5")
        self.lineEdit_b1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b1.setGeometry(QtCore.QRect(40, 80, 61, 33))
        self.lineEdit_b1.setObjectName("lineEdit_b1")
        self.lineEdit_b6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b6.setGeometry(QtCore.QRect(390, 80, 61, 33))
        self.lineEdit_b6.setObjectName("lineEdit_b6")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 21, 33))
        self.label_26.setObjectName("label_26")
        self.lineEdit_b2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b2.setGeometry(QtCore.QRect(110, 80, 61, 33))
        self.lineEdit_b2.setObjectName("lineEdit_b2")
        self.lineEdit_b4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b4.setGeometry(QtCore.QRect(250, 80, 61, 33))
        self.lineEdit_b4.setObjectName("lineEdit_b4")
        self.lineEdit_k4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_k4.setGeometry(QtCore.QRect(250, 120, 61, 33))
        self.lineEdit_k4.setObjectName("lineEdit_k4")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(10, 120, 21, 33))
        self.label_27.setObjectName("label_27")
        self.lineEdit_k2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_k2.setGeometry(QtCore.QRect(110, 120, 61, 33))
        self.lineEdit_k2.setObjectName("lineEdit_k2")
        self.lineEdit_k3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_k3.setGeometry(QtCore.QRect(180, 120, 61, 33))
        self.lineEdit_k3.setObjectName("lineEdit_k3")
        self.lineEdit_k5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_k5.setGeometry(QtCore.QRect(320, 120, 61, 33))
        self.lineEdit_k5.setObjectName("lineEdit_k5")
        self.lineEdit_k6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_k6.setGeometry(QtCore.QRect(390, 120, 61, 33))
        self.lineEdit_k6.setObjectName("lineEdit_k6")
        self.lineEdit_k1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_k1.setGeometry(QtCore.QRect(40, 120, 61, 33))
        self.lineEdit_k1.setObjectName("lineEdit_k1")
        self.lineEdit_i3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_i3.setGeometry(QtCore.QRect(180, 160, 61, 33))
        self.lineEdit_i3.setObjectName("lineEdit_i3")
        self.lineEdit_i5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_i5.setGeometry(QtCore.QRect(320, 160, 61, 33))
        self.lineEdit_i5.setObjectName("lineEdit_i5")
        self.lineEdit_i1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_i1.setGeometry(QtCore.QRect(40, 160, 61, 33))
        self.lineEdit_i1.setObjectName("lineEdit_i1")
        self.lineEdit_i6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_i6.setGeometry(QtCore.QRect(390, 160, 61, 33))
        self.lineEdit_i6.setObjectName("lineEdit_i6")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(10, 160, 21, 33))
        self.label_29.setObjectName("label_29")
        self.lineEdit_i2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_i2.setGeometry(QtCore.QRect(110, 160, 61, 33))
        self.lineEdit_i2.setObjectName("lineEdit_i2")
        self.lineEdit_i4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_i4.setGeometry(QtCore.QRect(250, 160, 61, 33))
        self.lineEdit_i4.setObjectName("lineEdit_i4")
        self.label_30 = QtWidgets.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(10, 150, 71, 33))
        self.label_30.setObjectName("label_30")
        self.lineEdit_pub_qq = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_pub_qq.setGeometry(QtCore.QRect(80, 150, 381, 41))
        self.lineEdit_pub_qq.setObjectName("lineEdit_pub_qq")
        self.horizontalLayout.addWidget(self.frame_6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(480, 430, 491, 401))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 451, 291))
        self.textEdit.setObjectName("textEdit")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(60, 340, 401, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 340, 51, 31))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 0, 111, 31))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 430, 391, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(0, 30, 181, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_x1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x1.setGeometry(QtCore.QRect(50, 50, 101, 33))
        self.lineEdit_x1.setObjectName("lineEdit_x1")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 151, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_21.setObjectName("label_21")
        self.lineEdit_x2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x2.setGeometry(QtCore.QRect(50, 100, 101, 33))
        self.lineEdit_x2.setObjectName("lineEdit_x2")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.label_22.setObjectName("label_22")
        self.lineEdit_x3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x3.setGeometry(QtCore.QRect(50, 150, 101, 33))
        self.lineEdit_x3.setObjectName("lineEdit_x3")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(10, 250, 31, 31))
        self.label_23.setObjectName("label_23")
        self.lineEdit_x5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x5.setGeometry(QtCore.QRect(50, 250, 101, 33))
        self.lineEdit_x5.setObjectName("lineEdit_x5")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(10, 300, 31, 31))
        self.label_24.setObjectName("label_24")
        self.lineEdit_x6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x6.setGeometry(QtCore.QRect(50, 300, 101, 33))
        self.lineEdit_x6.setObjectName("lineEdit_x6")
        self.lineEdit_x4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_x4.setGeometry(QtCore.QRect(50, 200, 101, 33))
        self.lineEdit_x4.setObjectName("lineEdit_x4")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.label_28.setObjectName("label_28")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(110, 0, 151, 31))
        self.label.setObjectName("label")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(190, 30, 181, 361))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.lineEdit_f1 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_f1.setGeometry(QtCore.QRect(50, 50, 101, 33))
        self.lineEdit_f1.setObjectName("lineEdit_f1")
        self.label_44 = QtWidgets.QLabel(self.frame_11)
        self.label_44.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_11)
        self.label_45.setGeometry(QtCore.QRect(10, 0, 151, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_11)
        self.label_46.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_46.setObjectName("label_46")
        self.lineEdit_f2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_f2.setGeometry(QtCore.QRect(50, 100, 101, 33))
        self.lineEdit_f2.setObjectName("lineEdit_f2")
        self.label_47 = QtWidgets.QLabel(self.frame_11)
        self.label_47.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.label_47.setObjectName("label_47")
        self.lineEdit_f3 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_f3.setGeometry(QtCore.QRect(50, 150, 101, 33))
        self.lineEdit_f3.setObjectName("lineEdit_f3")
        self.label_48 = QtWidgets.QLabel(self.frame_11)
        self.label_48.setGeometry(QtCore.QRect(10, 250, 31, 31))
        self.label_48.setObjectName("label_48")
        self.lineEdit_f5 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_f5.setGeometry(QtCore.QRect(50, 250, 101, 33))
        self.lineEdit_f5.setObjectName("lineEdit_f5")
        self.label_49 = QtWidgets.QLabel(self.frame_11)
        self.label_49.setGeometry(QtCore.QRect(10, 300, 31, 31))
        self.label_49.setObjectName("label_49")
        self.lineEdit_f6 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_f6.setGeometry(QtCore.QRect(50, 300, 101, 33))
        self.lineEdit_f6.setObjectName("lineEdit_f6")
        self.lineEdit_f4 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_f4.setGeometry(QtCore.QRect(50, 200, 101, 33))
        self.lineEdit_f4.setObjectName("lineEdit_f4")
        self.label_50 = QtWidgets.QLabel(self.frame_11)
        self.label_50.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.label_50.setObjectName("label_50")
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 0, 391, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setGeometry(QtCore.QRect(180, 0, 191, 411))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 171, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_end = QtWidgets.QPushButton(self.frame_5)
        self.button_end.setGeometry(QtCore.QRect(10, 100, 171, 61))
        self.button_end.setAutoDefault(True)
        self.button_end.setObjectName("button_end")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 180, 181, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_UR5 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_UR5.setObjectName("checkBox_UR5")
        self.verticalLayout_4.addWidget(self.checkBox_UR5)
        self.checkBox_real = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_real.setObjectName("checkBox_real")
        self.verticalLayout_4.addWidget(self.checkBox_real)
        self.button_read = QtWidgets.QPushButton(self.frame_5)
        self.button_read.setGeometry(QtCore.QRect(10, 300, 161, 61))
        self.button_read.setAutoDefault(True)
        self.button_read.setObjectName("button_read")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 161, 411))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 31, 33))
        self.label_11.setObjectName("label_11")
        self.lineEdit_q5 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q5.setGeometry(QtCore.QRect(50, 200, 81, 33))
        self.lineEdit_q5.setObjectName("lineEdit_q5")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 240, 31, 33))
        self.label_12.setObjectName("label_12")
        self.lineEdit_q6 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q6.setGeometry(QtCore.QRect(50, 240, 81, 33))
        self.lineEdit_q6.setObjectName("lineEdit_q6")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(10, 280, 31, 33))
        self.label_13.setObjectName("label_13")
        self.lineEdit_q7 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q7.setGeometry(QtCore.QRect(50, 280, 81, 33))
        self.lineEdit_q7.setObjectName("lineEdit_q7")
        self.lineEdit_q4 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q4.setGeometry(QtCore.QRect(50, 160, 81, 33))
        self.lineEdit_q4.setObjectName("lineEdit_q4")
        self.label_14 = QtWidgets.QLabel(self.frame_7)
        self.label_14.setGeometry(QtCore.QRect(10, 200, 31, 33))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(10, 0, 121, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(10, 120, 31, 33))
        self.label_16.setObjectName("label_16")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q3.setGeometry(QtCore.QRect(50, 120, 81, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 31, 33))
        self.label_17.setObjectName("label_17")
        self.lineEdit_q2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q2.setGeometry(QtCore.QRect(50, 80, 81, 33))
        self.lineEdit_q2.setObjectName("lineEdit_q2")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 31, 33))
        self.label_18.setObjectName("label_18")
        self.lineEdit_q1 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_q1.setGeometry(QtCore.QRect(50, 40, 81, 33))
        self.lineEdit_q1.setObjectName("lineEdit_q1")
        self.button_init = QtWidgets.QPushButton(self.frame_7)
        self.button_init.setGeometry(QtCore.QRect(20, 320, 111, 51))
        self.button_init.setAutoDefault(True)
        self.button_init.setObjectName("button_init")
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.lineEdit_q4.raise_()
        self.lineEdit_q5.raise_()
        self.lineEdit_q6.raise_()
        self.lineEdit_q7.raise_()
        self.lineEdit_q3.raise_()
        self.lineEdit_q2.raise_()
        self.lineEdit_q1.raise_()
        self.button_init.raise_()
        self.verticalLayout_2.addWidget(self.frame_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1399, 35))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Sub_qq:"))
        self.lineEdit_sub_qq.setText(_translate("MainWindow", "/robot3/joint_states"))
        self.label_9.setText(_translate("MainWindow", "Sub_F:"))
        self.lineEdit_sub_f.setText(_translate("MainWindow", "/robot3/ft_sensor_topic"))
        self.label_3.setText(_translate("MainWindow", "读取数据和话题地址"))
        self.label_2.setText(_translate("MainWindow", "自适应阻抗参数MBKI"))
        self.label_25.setText(_translate("MainWindow", "M:"))
        self.lineEdit_m1.setText(_translate("MainWindow", "0"))
        self.lineEdit_m6.setText(_translate("MainWindow", "0"))
        self.lineEdit_m5.setText(_translate("MainWindow", "0"))
        self.lineEdit_m4.setText(_translate("MainWindow", "0"))
        self.lineEdit_m3.setText(_translate("MainWindow", "0"))
        self.lineEdit_m2.setText(_translate("MainWindow", "0"))
        self.lineEdit_b3.setText(_translate("MainWindow", "0"))
        self.lineEdit_b5.setText(_translate("MainWindow", "0"))
        self.lineEdit_b1.setText(_translate("MainWindow", "0"))
        self.lineEdit_b6.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "B:"))
        self.lineEdit_b2.setText(_translate("MainWindow", "0"))
        self.lineEdit_b4.setText(_translate("MainWindow", "0"))
        self.lineEdit_k4.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "K:"))
        self.lineEdit_k2.setText(_translate("MainWindow", "0"))
        self.lineEdit_k3.setText(_translate("MainWindow", "0"))
        self.lineEdit_k5.setText(_translate("MainWindow", "0"))
        self.lineEdit_k6.setText(_translate("MainWindow", "0"))
        self.lineEdit_k1.setText(_translate("MainWindow", "0"))
        self.lineEdit_i3.setText(_translate("MainWindow", "0"))
        self.lineEdit_i5.setText(_translate("MainWindow", "0"))
        self.lineEdit_i1.setText(_translate("MainWindow", "0"))
        self.lineEdit_i6.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "I:"))
        self.lineEdit_i2.setText(_translate("MainWindow", "0"))
        self.lineEdit_i4.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Pub_qq:"))
        self.lineEdit_pub_qq.setText(_translate("MainWindow", "/robot3/armc_position_controller/command"))
        self.label_10.setText(_translate("MainWindow", "进度："))
        self.label_4.setText(_translate("MainWindow", "内容显示区域"))
        self.lineEdit_x1.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "X1："))
        self.label_20.setText(_translate("MainWindow", "操作空间：Xd/mm"))
        self.label_21.setText(_translate("MainWindow", "X2："))
        self.lineEdit_x2.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "X3："))
        self.lineEdit_x3.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "X5："))
        self.lineEdit_x5.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "X6："))
        self.lineEdit_x6.setText(_translate("MainWindow", "0"))
        self.lineEdit_x4.setText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "X4："))
        self.label.setText(_translate("MainWindow", "操作空间输入区域"))
        self.lineEdit_f1.setText(_translate("MainWindow", "0"))
        self.label_44.setText(_translate("MainWindow", "F1："))
        self.label_45.setText(_translate("MainWindow", "操作空间：Fd/N"))
        self.label_46.setText(_translate("MainWindow", "F2："))
        self.lineEdit_f2.setText(_translate("MainWindow", "0"))
        self.label_47.setText(_translate("MainWindow", "F3："))
        self.lineEdit_f3.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "F5："))
        self.lineEdit_f5.setText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "F6："))
        self.lineEdit_f6.setText(_translate("MainWindow", "0"))
        self.lineEdit_f4.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "F4："))
        self.button_begin.setText(_translate("MainWindow", "开始"))
        self.button_end.setText(_translate("MainWindow", "停止"))
        self.checkBox_UR5.setText(_translate("MainWindow", "UR5勾  armc默认"))
        self.checkBox_real.setText(_translate("MainWindow", "实物勾  仿真默认"))
        self.button_read.setText(_translate("MainWindow", "读取参数"))
        self.label_11.setText(_translate("MainWindow", "q4:"))
        self.lineEdit_q5.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "q6:"))
        self.lineEdit_q6.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "q7:"))
        self.lineEdit_q7.setText(_translate("MainWindow", "0"))
        self.lineEdit_q4.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "q5:"))
        self.label_15.setText(_translate("MainWindow", "初始关节角q/°"))
        self.label_16.setText(_translate("MainWindow", "q3:"))
        self.lineEdit_q3.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "q2:"))
        self.lineEdit_q2.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "q1:"))
        self.lineEdit_q1.setText(_translate("MainWindow", "0"))
        self.button_init.setText(_translate("MainWindow", "计算起点"))

