# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windon.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 903)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 431))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 431))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 461, 301))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 0, 131, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(70, 360, 401, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 360, 51, 31))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 511, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 491, 241))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(170, 10, 161, 31))
        self.label_11.setObjectName("label_11")
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setGeometry(QtCore.QRect(10, 160, 71, 33))
        self.label_30.setObjectName("label_30")
        self.lineEdit_sub_f = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_sub_f.setGeometry(QtCore.QRect(80, 40, 381, 41))
        self.lineEdit_sub_f.setObjectName("lineEdit_sub_f")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 61, 33))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 71, 33))
        self.label_13.setObjectName("label_13")
        self.lineEdit_sub_qq = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_sub_qq.setGeometry(QtCore.QRect(80, 100, 381, 41))
        self.lineEdit_sub_qq.setObjectName("lineEdit_sub_qq")
        self.lineEdit_pub_qq = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_pub_qq.setGeometry(QtCore.QRect(80, 160, 381, 41))
        self.lineEdit_pub_qq.setObjectName("lineEdit_pub_qq")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.button_receive = QtWidgets.QPushButton(self.frame_4)
        self.button_receive.setGeometry(QtCore.QRect(130, 290, 221, 61))
        self.button_receive.setIconSize(QtCore.QSize(16, 16))
        self.button_receive.setAutoRepeat(False)
        self.button_receive.setAutoExclusive(False)
        self.button_receive.setAutoRepeatDelay(400)
        self.button_receive.setAutoRepeatInterval(200)
        self.button_receive.setAutoDefault(True)
        self.button_receive.setFlat(False)
        self.button_receive.setObjectName("button_receive")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 31, 33))
        self.label_4.setObjectName("label_4")
        self.lineEdit_q5 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q5.setGeometry(QtCore.QRect(50, 210, 181, 33))
        self.lineEdit_q5.setObjectName("lineEdit_q5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 31, 33))
        self.label_5.setObjectName("label_5")
        self.lineEdit_q6 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q6.setGeometry(QtCore.QRect(50, 260, 181, 33))
        self.lineEdit_q6.setObjectName("lineEdit_q6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 31, 33))
        self.label_6.setObjectName("label_6")
        self.lineEdit_q7 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q7.setGeometry(QtCore.QRect(50, 300, 181, 33))
        self.lineEdit_q7.setObjectName("lineEdit_q7")
        self.lineEdit_q4 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q4.setGeometry(QtCore.QRect(50, 160, 180, 33))
        self.lineEdit_q4.setObjectName("lineEdit_q4")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 31, 33))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(60, 0, 151, 31))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 31, 33))
        self.label_8.setObjectName("label_8")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q3.setGeometry(QtCore.QRect(50, 120, 180, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 31, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_q2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q2.setGeometry(QtCore.QRect(50, 80, 180, 33))
        self.lineEdit_q2.setObjectName("lineEdit_q2")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 31, 33))
        self.label_10.setObjectName("label_10")
        self.lineEdit_q1 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q1.setGeometry(QtCore.QRect(50, 40, 180, 33))
        self.lineEdit_q1.setObjectName("lineEdit_q1")
        self.button_wish_pos = QtWidgets.QPushButton(self.frame_6)
        self.button_wish_pos.setGeometry(QtCore.QRect(90, 360, 91, 41))
        self.button_wish_pos.setAutoDefault(True)
        self.button_wish_pos.setObjectName("button_wish_pos")
        self.lineEdit_q4.raise_()
        self.label_4.raise_()
        self.lineEdit_q5.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.lineEdit_q6.raise_()
        self.label_6.raise_()
        self.lineEdit_q7.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.lineEdit_q3.raise_()
        self.label_9.raise_()
        self.lineEdit_q2.raise_()
        self.label_10.raise_()
        self.lineEdit_q1.raise_()
        self.button_wish_pos.raise_()
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 200, 201, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_UR5 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_UR5.setObjectName("checkBox_UR5")
        self.verticalLayout_4.addWidget(self.checkBox_UR5)
        self.checkBox_gazebo = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_gazebo.setObjectName("checkBox_gazebo")
        self.verticalLayout_4.addWidget(self.checkBox_gazebo)
        self.button_plan = QtWidgets.QPushButton(self.frame_5)
        self.button_plan.setGeometry(QtCore.QRect(10, 300, 221, 61))
        self.button_plan.setAutoDefault(True)
        self.button_plan.setObjectName("button_plan")
        self.verticalLayout_2.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "运行内容显示框"))
        self.label_2.setText(_translate("MainWindow", "进度："))
        self.label_11.setText(_translate("MainWindow", "读取数据和话题地址"))
        self.label_30.setText(_translate("MainWindow", "Pub_qq:"))
        self.lineEdit_sub_f.setText(_translate("MainWindow", "/ft_sensor_topic"))
        self.label_12.setText(_translate("MainWindow", "Sub_F:"))
        self.label_13.setText(_translate("MainWindow", "Sub_qq:"))
        self.lineEdit_sub_qq.setText(_translate("MainWindow", "/armc/joint_states"))
        self.lineEdit_pub_qq.setText(_translate("MainWindow", "/armc/joint_positions_controller/command"))
        self.button_receive.setText(_translate("MainWindow", "接收机器人状态"))
        self.label_4.setText(_translate("MainWindow", "q4:"))
        self.lineEdit_q5.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "q6:"))
        self.lineEdit_q6.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "q7:"))
        self.lineEdit_q7.setText(_translate("MainWindow", "0"))
        self.lineEdit_q4.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "q5:"))
        self.label_3.setText(_translate("MainWindow", "给定关节角q/°"))
        self.label_8.setText(_translate("MainWindow", "q3:"))
        self.lineEdit_q3.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "q2:"))
        self.lineEdit_q2.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "q1:"))
        self.lineEdit_q1.setText(_translate("MainWindow", "0"))
        self.button_wish_pos.setText(_translate("MainWindow", "目标点"))
        self.button_begin.setText(_translate("MainWindow", "开始"))
        self.button_stop.setText(_translate("MainWindow", "停止"))
        self.checkBox_UR5.setText(_translate("MainWindow", "UR5勾   armc默认"))
        self.checkBox_gazebo.setText(_translate("MainWindow", "仿真勾   实物默认"))
        self.button_plan.setText(_translate("MainWindow", "规划"))

