# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urs_form2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UrsForm2(object):
    def setupUi(self, UrsForm2):
        UrsForm2.setObjectName("UrsForm2")
        UrsForm2.resize(1238, 903)
        UrsForm2.setIconSize(QtCore.QSize(16, 16))
        UrsForm2.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(UrsForm2)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 421))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 471, 191))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 0, 131, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(70, 240, 411, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 240, 51, 31))
        self.label_15.setObjectName("label_15")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 290, 469, 91))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(120, 0, 231, 31))
        self.label_19.setObjectName("label_19")
        self.radioButton_robot1_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_robot1_2.setGeometry(QtCore.QRect(90, 40, 91, 25))
        self.radioButton_robot1_2.setObjectName("radioButton_robot1_2")
        self.radioButton_robot2_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_robot2_2.setGeometry(QtCore.QRect(290, 40, 91, 25))
        self.radioButton_robot2_2.setObjectName("radioButton_robot2_2")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 511, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(10, 160, 469, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(160, 0, 151, 31))
        self.label_18.setObjectName("label_18")
        self.radioButton_robot1 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot1.setGeometry(QtCore.QRect(20, 40, 91, 25))
        self.radioButton_robot1.setObjectName("radioButton_robot1")
        self.radioButton_robot2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot2.setGeometry(QtCore.QRect(190, 40, 91, 25))
        self.radioButton_robot2.setObjectName("radioButton_robot2")
        self.radioButton_all = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_all.setGeometry(QtCore.QRect(350, 40, 91, 25))
        self.radioButton_all.setObjectName("radioButton_all")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setGeometry(QtCore.QRect(10, 260, 469, 101))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(240, 40, 91, 31))
        self.label_14.setObjectName("label_14")
        self.lineEdit_t = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_t.setGeometry(QtCore.QRect(330, 40, 101, 33))
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.lineEdit_T = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_T.setGeometry(QtCore.QRect(110, 40, 101, 33))
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 91, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(130, 0, 239, 21))
        self.label_13.setObjectName("label_13")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 469, 141))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(10, 90, 91, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit_data_2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_data_2.setGeometry(QtCore.QRect(100, 90, 341, 33))
        self.lineEdit_data_2.setObjectName("lineEdit_data_2")
        self.lineEdit_data_1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_data_1.setGeometry(QtCore.QRect(100, 40, 341, 33))
        self.lineEdit_data_1.setObjectName("lineEdit_data_1")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 91, 31))
        self.label_17.setObjectName("label_17")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(200, 0, 81, 21))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(110, 0, 61, 31))
        self.label_3.setObjectName("label_3")
        self.button_init_plan = QtWidgets.QPushButton(self.frame_6)
        self.button_init_plan.setGeometry(QtCore.QRect(60, 110, 141, 51))
        self.button_init_plan.setAutoDefault(True)
        self.button_init_plan.setObjectName("button_init_plan")
        self.button_work = QtWidgets.QPushButton(self.frame_6)
        self.button_work.setGeometry(QtCore.QRect(60, 180, 141, 51))
        self.button_work.setAutoDefault(True)
        self.button_work.setObjectName("button_work")
        self.button_end_plan = QtWidgets.QPushButton(self.frame_6)
        self.button_end_plan.setGeometry(QtCore.QRect(60, 250, 141, 51))
        self.button_end_plan.setAutoDefault(True)
        self.button_end_plan.setObjectName("button_end_plan")
        self.button_refresh = QtWidgets.QPushButton(self.frame_6)
        self.button_refresh.setGeometry(QtCore.QRect(30, 320, 201, 51))
        self.button_refresh.setAutoDefault(True)
        self.button_refresh.setObjectName("button_refresh")
        self.button_read_data = QtWidgets.QPushButton(self.frame_6)
        self.button_read_data.setGeometry(QtCore.QRect(20, 40, 211, 61))
        self.button_read_data.setAutoDefault(True)
        self.button_read_data.setObjectName("button_read_data")
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 190, 211, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.radioButton_real = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_real.setGeometry(QtCore.QRect(10, 10, 71, 32))
        self.radioButton_real.setObjectName("radioButton_real")
        self.radioButton_gazebo = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_gazebo.setGeometry(QtCore.QRect(100, 10, 71, 32))
        self.radioButton_gazebo.setObjectName("radioButton_gazebo")
        self.verticalLayout_4.addWidget(self.frame_8)
        self.button_receive = QtWidgets.QPushButton(self.frame_5)
        self.button_receive.setGeometry(QtCore.QRect(50, 300, 161, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.verticalLayout_2.addWidget(self.frame_5)
        UrsForm2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UrsForm2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        UrsForm2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UrsForm2)
        self.statusbar.setObjectName("statusbar")
        UrsForm2.setStatusBar(self.statusbar)

        self.retranslateUi(UrsForm2)
        QtCore.QMetaObject.connectSlotsByName(UrsForm2)

    def retranslateUi(self, UrsForm2):
        _translate = QtCore.QCoreApplication.translate
        UrsForm2.setWindowTitle(_translate("UrsForm2", "MainWindow"))
        self.label.setText(_translate("UrsForm2", "运行内容显示框"))
        self.label_15.setText(_translate("UrsForm2", "进度："))
        self.label_19.setText(_translate("UrsForm2", "选择需要绘制状态图机械臂"))
        self.radioButton_robot1_2.setText(_translate("UrsForm2", "robot1"))
        self.radioButton_robot2_2.setText(_translate("UrsForm2", "robot2"))
        self.label_18.setText(_translate("UrsForm2", "选择操作的机械臂"))
        self.radioButton_robot1.setText(_translate("UrsForm2", "robot1"))
        self.radioButton_robot2.setText(_translate("UrsForm2", "robot2"))
        self.radioButton_all.setText(_translate("UrsForm2", "all"))
        self.label_14.setText(_translate("UrsForm2", "规划时间："))
        self.lineEdit_t.setText(_translate("UrsForm2", "10"))
        self.lineEdit_T.setText(_translate("UrsForm2", "0.01"))
        self.label_12.setText(_translate("UrsForm2", "规划周期："))
        self.label_13.setText(_translate("UrsForm2", "规划时间参数：单位/s"))
        self.label_16.setText(_translate("UrsForm2", "data_dir2："))
        self.lineEdit_data_2.setText(_translate("UrsForm2", "/home/d/catkin_ws/src/robot_python/data/robots/robot2_position.txt"))
        self.lineEdit_data_1.setText(_translate("UrsForm2", "/home/d/catkin_ws/src/robot_python/data/robots/robot1_position.txt"))
        self.label_17.setText(_translate("UrsForm2", "data_dir1："))
        self.label_20.setText(_translate("UrsForm2", "数据地址"))
        self.label_3.setText(_translate("UrsForm2", "操作栏"))
        self.button_init_plan.setText(_translate("UrsForm2", "起始段规划"))
        self.button_work.setText(_translate("UrsForm2", "切换到轨迹段"))
        self.button_end_plan.setText(_translate("UrsForm2", "返回端规划"))
        self.button_refresh.setText(_translate("UrsForm2", "刷新选择按钮"))
        self.button_read_data.setText(_translate("UrsForm2", "读取规划数据"))
        self.button_begin.setText(_translate("UrsForm2", "开始"))
        self.button_stop.setText(_translate("UrsForm2", "停止"))
        self.radioButton_real.setText(_translate("UrsForm2", "实物"))
        self.radioButton_gazebo.setText(_translate("UrsForm2", "仿真"))
        self.button_receive.setText(_translate("UrsForm2", "接收机器人状态"))

