set(_CATKIN_CURRENT_PACKAGE "impedance_controler")
set(impedance_controler_VERSION "0.0.0")
set(impedance_controler_MAINTAINER "d <d@todo.todo>")
set(impedance_controler_PACKAGE_FORMAT "2")
set(impedance_controler_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "controller_interface" "hardware_interface" "pluginlib")
set(impedance_controler_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "controller_interface" "hardware_interface" "pluginlib")
set(impedance_controler_BUILDTOOL_DEPENDS "catkin")
set(impedance_controler_BUILDTOOL_EXPORT_DEPENDS )
set(impedance_controler_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "controller_interface" "hardware_interface" "pluginlib")
set(impedance_controler_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "controller_interface" "hardware_interface" "pluginlib")
set(impedance_controler_TEST_DEPENDS )
set(impedance_controler_DOC_DEPENDS )
set(impedance_controler_URL_WEBSITE "")
set(impedance_controler_URL_BUGTRACKER "")
set(impedance_controler_URL_REPOSITORY "")
set(impedance_controler_DEPRECATED "")