set(_CATKIN_CURRENT_PACKAGE "c_lightcobot")
set(c_lightcobot_VERSION "0.0.0")
set(c_lightcobot_MAINTAINER "Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(c_lightcobot_PACKAGE_FORMAT "1")
set(c_lightcobot_BUILD_DEPENDS )
set(c_lightcobot_BUILD_EXPORT_DEPENDS "armc_gazebo" "arm_description")
set(c_lightcobot_BUILDTOOL_DEPENDS "catkin")
set(c_lightcobot_BUILDTOOL_EXPORT_DEPENDS )
set(c_lightcobot_EXEC_DEPENDS "armc_gazebo" "arm_description")
set(c_lightcobot_RUN_DEPENDS "armc_gazebo" "arm_description")
set(c_lightcobot_TEST_DEPENDS )
set(c_lightcobot_DOC_DEPENDS )
set(c_lightcobot_URL_WEBSITE "")
set(c_lightcobot_URL_BUGTRACKER "")
set(c_lightcobot_URL_REPOSITORY "")
set(c_lightcobot_DEPRECATED "")