// Generated by gencpp from file armc_controller/SetArmcConfigure.msg
// DO NOT EDIT!


#ifndef ARMC_CONTROLLER_MESSAGE_SETARMCCONFIGURE_H
#define ARMC_CONTROLLER_MESSAGE_SETARMCCONFIGURE_H

#include <ros/service_traits.h>


#include <armc_controller/SetArmcConfigureRequest.h>
#include <armc_controller/SetArmcConfigureResponse.h>


namespace armc_controller
{

struct SetArmcConfigure
{

typedef SetArmcConfigureRequest Request;
typedef SetArmcConfigureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetArmcConfigure
} // namespace armc_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armc_controller::SetArmcConfigure > {
  static const char* value()
  {
    return "e4d1173ab6495a30091da13a92937cf6";
  }

  static const char* value(const ::armc_controller::SetArmcConfigure&) { return value(); }
};

template<>
struct DataType< ::armc_controller::SetArmcConfigure > {
  static const char* value()
  {
    return "armc_controller/SetArmcConfigure";
  }

  static const char* value(const ::armc_controller::SetArmcConfigure&) { return value(); }
};


// service_traits::MD5Sum< ::armc_controller::SetArmcConfigureRequest> should match 
// service_traits::MD5Sum< ::armc_controller::SetArmcConfigure > 
template<>
struct MD5Sum< ::armc_controller::SetArmcConfigureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armc_controller::SetArmcConfigure >::value();
  }
  static const char* value(const ::armc_controller::SetArmcConfigureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armc_controller::SetArmcConfigureRequest> should match 
// service_traits::DataType< ::armc_controller::SetArmcConfigure > 
template<>
struct DataType< ::armc_controller::SetArmcConfigureRequest>
{
  static const char* value()
  {
    return DataType< ::armc_controller::SetArmcConfigure >::value();
  }
  static const char* value(const ::armc_controller::SetArmcConfigureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armc_controller::SetArmcConfigureResponse> should match 
// service_traits::MD5Sum< ::armc_controller::SetArmcConfigure > 
template<>
struct MD5Sum< ::armc_controller::SetArmcConfigureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armc_controller::SetArmcConfigure >::value();
  }
  static const char* value(const ::armc_controller::SetArmcConfigureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armc_controller::SetArmcConfigureResponse> should match 
// service_traits::DataType< ::armc_controller::SetArmcConfigure > 
template<>
struct DataType< ::armc_controller::SetArmcConfigureResponse>
{
  static const char* value()
  {
    return DataType< ::armc_controller::SetArmcConfigure >::value();
  }
  static const char* value(const ::armc_controller::SetArmcConfigureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMC_CONTROLLER_MESSAGE_SETARMCCONFIGURE_H
