set(hrl_geom_SETUP_PY_VERSION "0.1.0")
set(hrl_geom_SETUP_PY_SCRIPTS "")
set(hrl_geom_SETUP_PY_PACKAGES "hrl_geom")
set(hrl_geom_SETUP_PY_PACKAGE_DIRS "src/hrl_geom")
set(hrl_geom_SETUP_PY_MODULES "")
set(hrl_geom_SETUP_PY_MODULE_DIRS "")