set(_CATKIN_CURRENT_PACKAGE "ros_ethercat_driver")
set(ros_ethercat_driver_VERSION "0.0.0")
set(ros_ethercat_driver_MAINTAINER "hitstar <hitstar@todo.todo>")
set(ros_ethercat_driver_PACKAGE_FORMAT "2")
set(ros_ethercat_driver_BUILD_DEPENDS "roscpp" "soem" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_ethercat_driver_BUILD_EXPORT_DEPENDS "roscpp" "soem" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_ethercat_driver_BUILDTOOL_DEPENDS "catkin")
set(ros_ethercat_driver_BUILDTOOL_EXPORT_DEPENDS )
set(ros_ethercat_driver_EXEC_DEPENDS "roscpp" "soem" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_ethercat_driver_RUN_DEPENDS "roscpp" "soem" "controller_interface" "pluginlib" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "urdf")
set(ros_ethercat_driver_TEST_DEPENDS )
set(ros_ethercat_driver_DOC_DEPENDS )
set(ros_ethercat_driver_URL_WEBSITE "")
set(ros_ethercat_driver_URL_BUGTRACKER "")
set(ros_ethercat_driver_URL_REPOSITORY "")
set(ros_ethercat_driver_DEPRECATED "")