# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armct_form1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArmctForm1(object):
    def setupUi(self, ArmctForm1):
        ArmctForm1.setObjectName("ArmctForm1")
        ArmctForm1.resize(1238, 903)
        ArmctForm1.setIconSize(QtCore.QSize(16, 16))
        ArmctForm1.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(ArmctForm1)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 451, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(460, 410, 511, 421))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 471, 191))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 0, 131, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(70, 240, 411, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 240, 51, 31))
        self.label_15.setObjectName("label_15")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 290, 469, 91))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(120, 0, 231, 31))
        self.label_19.setObjectName("label_19")
        self.radioButton_robot1_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_robot1_2.setGeometry(QtCore.QRect(70, 40, 91, 25))
        self.radioButton_robot1_2.setObjectName("radioButton_robot1_2")
        self.radioButton_robot2_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_robot2_2.setGeometry(QtCore.QRect(310, 40, 91, 25))
        self.radioButton_robot2_2.setObjectName("radioButton_robot2_2")
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(460, 10, 511, 401))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 471, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(240, 40, 91, 31))
        self.label_14.setObjectName("label_14")
        self.lineEdit_t = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_t.setGeometry(QtCore.QRect(330, 40, 101, 33))
        self.lineEdit_t.setObjectName("lineEdit_t")
        self.lineEdit_T = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_T.setGeometry(QtCore.QRect(110, 40, 101, 33))
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 91, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(130, 0, 239, 21))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.button_receive = QtWidgets.QPushButton(self.frame_4)
        self.button_receive.setGeometry(QtCore.QRect(40, 310, 161, 61))
        self.button_receive.setAutoDefault(True)
        self.button_receive.setObjectName("button_receive")
        self.button_init = QtWidgets.QPushButton(self.frame_4)
        self.button_init.setGeometry(QtCore.QRect(120, 250, 91, 51))
        self.button_init.setAutoDefault(True)
        self.button_init.setObjectName("button_init")
        self.button_home = QtWidgets.QPushButton(self.frame_4)
        self.button_home.setGeometry(QtCore.QRect(270, 250, 91, 51))
        self.button_home.setAutoDefault(True)
        self.button_home.setObjectName("button_home")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 129, 471, 111))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(160, 0, 151, 31))
        self.label_18.setObjectName("label_18")
        self.radioButton_robot1 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot1.setGeometry(QtCore.QRect(40, 40, 91, 25))
        self.radioButton_robot1.setObjectName("radioButton_robot1")
        self.radioButton_robot2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot2.setGeometry(QtCore.QRect(190, 40, 91, 25))
        self.radioButton_robot2.setObjectName("radioButton_robot2")
        self.radioButton_robot2_3 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_robot2_3.setGeometry(QtCore.QRect(320, 40, 91, 25))
        self.radioButton_robot2_3.setObjectName("radioButton_robot2_3")
        self.horizontalLayout.addWidget(self.frame_2)
        self.button_refresh = QtWidgets.QPushButton(self.frame_4)
        self.button_refresh.setGeometry(QtCore.QRect(280, 310, 161, 61))
        self.button_refresh.setAutoDefault(True)
        self.button_refresh.setObjectName("button_refresh")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(970, 410, 261, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 31, 33))
        self.label_4.setObjectName("label_4")
        self.lineEdit_q5 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q5.setGeometry(QtCore.QRect(50, 200, 181, 33))
        self.lineEdit_q5.setObjectName("lineEdit_q5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 31, 33))
        self.label_5.setObjectName("label_5")
        self.lineEdit_q6 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q6.setGeometry(QtCore.QRect(50, 240, 181, 33))
        self.lineEdit_q6.setObjectName("lineEdit_q6")
        self.lineEdit_q4 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q4.setGeometry(QtCore.QRect(50, 160, 180, 33))
        self.lineEdit_q4.setObjectName("lineEdit_q4")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 31, 33))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(70, 0, 121, 31))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 31, 33))
        self.label_8.setObjectName("label_8")
        self.lineEdit_q3 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q3.setGeometry(QtCore.QRect(50, 120, 180, 33))
        self.lineEdit_q3.setObjectName("lineEdit_q3")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 31, 33))
        self.label_9.setObjectName("label_9")
        self.lineEdit_q2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q2.setGeometry(QtCore.QRect(50, 80, 180, 33))
        self.lineEdit_q2.setObjectName("lineEdit_q2")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 31, 33))
        self.label_10.setObjectName("label_10")
        self.lineEdit_q1 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q1.setGeometry(QtCore.QRect(50, 40, 180, 33))
        self.lineEdit_q1.setObjectName("lineEdit_q1")
        self.button_read = QtWidgets.QPushButton(self.frame_6)
        self.button_read.setGeometry(QtCore.QRect(80, 340, 121, 51))
        self.button_read.setAutoDefault(True)
        self.button_read.setObjectName("button_read")
        self.lineEdit_q7 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_q7.setGeometry(QtCore.QRect(50, 280, 181, 33))
        self.lineEdit_q7.setObjectName("lineEdit_q7")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 31, 33))
        self.label_6.setObjectName("label_6")
        self.lineEdit_q4.raise_()
        self.label_4.raise_()
        self.lineEdit_q5.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.lineEdit_q6.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.lineEdit_q3.raise_()
        self.label_9.raise_()
        self.lineEdit_q2.raise_()
        self.label_10.raise_()
        self.lineEdit_q1.raise_()
        self.button_read.raise_()
        self.lineEdit_q7.raise_()
        self.label_6.raise_()
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(970, 10, 261, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.button_begin = QtWidgets.QPushButton(self.frame_5)
        self.button_begin.setGeometry(QtCore.QRect(10, 20, 221, 61))
        self.button_begin.setIconSize(QtCore.QSize(16, 16))
        self.button_begin.setAutoRepeat(False)
        self.button_begin.setAutoExclusive(False)
        self.button_begin.setAutoRepeatDelay(400)
        self.button_begin.setAutoRepeatInterval(200)
        self.button_begin.setAutoDefault(True)
        self.button_begin.setFlat(False)
        self.button_begin.setObjectName("button_begin")
        self.button_stop = QtWidgets.QPushButton(self.frame_5)
        self.button_stop.setGeometry(QtCore.QRect(10, 110, 221, 61))
        self.button_stop.setAutoDefault(True)
        self.button_stop.setObjectName("button_stop")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 190, 211, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.radioButton_real = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_real.setGeometry(QtCore.QRect(20, 10, 71, 32))
        self.radioButton_real.setObjectName("radioButton_real")
        self.radioButton_gazebo = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_gazebo.setGeometry(QtCore.QRect(110, 10, 71, 32))
        self.radioButton_gazebo.setObjectName("radioButton_gazebo")
        self.verticalLayout_4.addWidget(self.frame_8)
        self.button_plan = QtWidgets.QPushButton(self.frame_5)
        self.button_plan.setGeometry(QtCore.QRect(20, 290, 211, 61))
        self.button_plan.setAutoDefault(True)
        self.button_plan.setObjectName("button_plan")
        self.verticalLayout_2.addWidget(self.frame_5)
        ArmctForm1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArmctForm1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1238, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        ArmctForm1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArmctForm1)
        self.statusbar.setObjectName("statusbar")
        ArmctForm1.setStatusBar(self.statusbar)

        self.retranslateUi(ArmctForm1)
        QtCore.QMetaObject.connectSlotsByName(ArmctForm1)

    def retranslateUi(self, ArmctForm1):
        _translate = QtCore.QCoreApplication.translate
        ArmctForm1.setWindowTitle(_translate("ArmctForm1", "MainWindow"))
        self.label.setText(_translate("ArmctForm1", "运行内容显示框"))
        self.label_15.setText(_translate("ArmctForm1", "进度："))
        self.label_19.setText(_translate("ArmctForm1", "选择需要绘制状态图机械臂"))
        self.radioButton_robot1_2.setText(_translate("ArmctForm1", "armt"))
        self.radioButton_robot2_2.setText(_translate("ArmctForm1", "armc"))
        self.label_14.setText(_translate("ArmctForm1", "规划时间："))
        self.lineEdit_t.setText(_translate("ArmctForm1", "10"))
        self.lineEdit_T.setText(_translate("ArmctForm1", "0.01"))
        self.label_12.setText(_translate("ArmctForm1", "规划周期："))
        self.label_13.setText(_translate("ArmctForm1", "规划时间参数：单位/s"))
        self.button_receive.setText(_translate("ArmctForm1", "接收机器人状态"))
        self.button_init.setText(_translate("ArmctForm1", "init"))
        self.button_home.setText(_translate("ArmctForm1", "home"))
        self.label_18.setText(_translate("ArmctForm1", "选择操作的机械臂"))
        self.radioButton_robot1.setText(_translate("ArmctForm1", "armt"))
        self.radioButton_robot2.setText(_translate("ArmctForm1", "armc"))
        self.radioButton_robot2_3.setText(_translate("ArmctForm1", "all"))
        self.button_refresh.setText(_translate("ArmctForm1", "刷新选择按钮"))
        self.label_4.setText(_translate("ArmctForm1", "q4:"))
        self.lineEdit_q5.setText(_translate("ArmctForm1", "0"))
        self.label_5.setText(_translate("ArmctForm1", "q6:"))
        self.lineEdit_q6.setText(_translate("ArmctForm1", "0"))
        self.lineEdit_q4.setText(_translate("ArmctForm1", "0"))
        self.label_7.setText(_translate("ArmctForm1", "q5:"))
        self.label_3.setText(_translate("ArmctForm1", "规划关节角q/°"))
        self.label_8.setText(_translate("ArmctForm1", "q3:"))
        self.lineEdit_q3.setText(_translate("ArmctForm1", "0"))
        self.label_9.setText(_translate("ArmctForm1", "q2:"))
        self.lineEdit_q2.setText(_translate("ArmctForm1", "0"))
        self.label_10.setText(_translate("ArmctForm1", "q1:"))
        self.lineEdit_q1.setText(_translate("ArmctForm1", "0"))
        self.button_read.setText(_translate("ArmctForm1", "读取目标点"))
        self.lineEdit_q7.setText(_translate("ArmctForm1", "0"))
        self.label_6.setText(_translate("ArmctForm1", "q7:"))
        self.button_begin.setText(_translate("ArmctForm1", "开始"))
        self.button_stop.setText(_translate("ArmctForm1", "停止"))
        self.radioButton_real.setText(_translate("ArmctForm1", "实物"))
        self.radioButton_gazebo.setText(_translate("ArmctForm1", "仿真"))
        self.button_plan.setText(_translate("ArmctForm1", "规划"))

