// Generated by gencpp from file action_test/action_srv1.msg
// DO NOT EDIT!


#ifndef ACTION_TEST_MESSAGE_ACTION_SRV1_H
#define ACTION_TEST_MESSAGE_ACTION_SRV1_H

#include <ros/service_traits.h>


#include <action_test/action_srv1Request.h>
#include <action_test/action_srv1Response.h>


namespace action_test
{

struct action_srv1
{

typedef action_srv1Request Request;
typedef action_srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct action_srv1
} // namespace action_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::action_test::action_srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::action_test::action_srv1&) { return value(); }
};

template<>
struct DataType< ::action_test::action_srv1 > {
  static const char* value()
  {
    return "action_test/action_srv1";
  }

  static const char* value(const ::action_test::action_srv1&) { return value(); }
};


// service_traits::MD5Sum< ::action_test::action_srv1Request> should match 
// service_traits::MD5Sum< ::action_test::action_srv1 > 
template<>
struct MD5Sum< ::action_test::action_srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::action_test::action_srv1 >::value();
  }
  static const char* value(const ::action_test::action_srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_test::action_srv1Request> should match 
// service_traits::DataType< ::action_test::action_srv1 > 
template<>
struct DataType< ::action_test::action_srv1Request>
{
  static const char* value()
  {
    return DataType< ::action_test::action_srv1 >::value();
  }
  static const char* value(const ::action_test::action_srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::action_test::action_srv1Response> should match 
// service_traits::MD5Sum< ::action_test::action_srv1 > 
template<>
struct MD5Sum< ::action_test::action_srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::action_test::action_srv1 >::value();
  }
  static const char* value(const ::action_test::action_srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_test::action_srv1Response> should match 
// service_traits::DataType< ::action_test::action_srv1 > 
template<>
struct DataType< ::action_test::action_srv1Response>
{
  static const char* value()
  {
    return DataType< ::action_test::action_srv1 >::value();
  }
  static const char* value(const ::action_test::action_srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_TEST_MESSAGE_ACTION_SRV1_H
