set(_CATKIN_CURRENT_PACKAGE "pykdl_utils")
set(pykdl_utils_VERSION "0.1.0")
set(pykdl_utils_MAINTAINER "Kelsey Hawkins <kphawkins@gatech.edu>")
set(pykdl_utils_PACKAGE_FORMAT "1")
set(pykdl_utils_BUILD_DEPENDS "geometry_msgs" "hrl_geom" "rospy" "sensor_msgs" "tf" "urdfdom_py")
set(pykdl_utils_BUILD_EXPORT_DEPENDS "geometry_msgs" "hrl_geom" "rospy" "sensor_msgs" "tf" "urdfdom_py")
set(pykdl_utils_BUILDTOOL_DEPENDS "catkin")
set(pykdl_utils_BUILDTOOL_EXPORT_DEPENDS )
set(pykdl_utils_EXEC_DEPENDS "geometry_msgs" "hrl_geom" "rospy" "sensor_msgs" "tf" "urdfdom_py")
set(pykdl_utils_RUN_DEPENDS "geometry_msgs" "hrl_geom" "rospy" "sensor_msgs" "tf" "urdfdom_py")
set(pykdl_utils_TEST_DEPENDS )
set(pykdl_utils_DOC_DEPENDS )
set(pykdl_utils_URL_WEBSITE "http://ros.org/wiki/pykdl_utils")
set(pykdl_utils_URL_BUGTRACKER "")
set(pykdl_utils_URL_REPOSITORY "")
set(pykdl_utils_DEPRECATED "")