set(pykdl_utils_SETUP_PY_VERSION "0.1.0")
set(pykdl_utils_SETUP_PY_SCRIPTS "")
set(pykdl_utils_SETUP_PY_PACKAGES "pykdl_utils")
set(pykdl_utils_SETUP_PY_PACKAGE_DIRS "src/pykdl_utils")
set(pykdl_utils_SETUP_PY_MODULES "")
set(pykdl_utils_SETUP_PY_MODULE_DIRS "")