set(_CATKIN_CURRENT_PACKAGE "hrl_kdl")
set(hrl_kdl_VERSION "0.0.0")
set(hrl_kdl_MAINTAINER "Kelsey Hawkins <kphawkins@gatech.edu>")
set(hrl_kdl_PACKAGE_FORMAT "1")
set(hrl_kdl_BUILD_DEPENDS )
set(hrl_kdl_BUILD_EXPORT_DEPENDS "hrl_geom" "pykdl_utils")
set(hrl_kdl_BUILDTOOL_DEPENDS "catkin")
set(hrl_kdl_BUILDTOOL_EXPORT_DEPENDS )
set(hrl_kdl_EXEC_DEPENDS "hrl_geom" "pykdl_utils")
set(hrl_kdl_RUN_DEPENDS "hrl_geom" "pykdl_utils")
set(hrl_kdl_TEST_DEPENDS )
set(hrl_kdl_DOC_DEPENDS )
set(hrl_kdl_URL_WEBSITE "http://ros.org/wiki/hrl_kdl")
set(hrl_kdl_URL_BUGTRACKER "")
set(hrl_kdl_URL_REPOSITORY "")
set(hrl_kdl_DEPRECATED "")