set(_CATKIN_CURRENT_PACKAGE "action_test")
set(action_test_VERSION "0.0.0")
set(action_test_MAINTAINER "d <d@todo.todo>")
set(action_test_PACKAGE_FORMAT "2")
set(action_test_BUILD_DEPENDS "message_generation" "roscpp" "std_msgs")
set(action_test_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(action_test_BUILDTOOL_DEPENDS "catkin")
set(action_test_BUILDTOOL_EXPORT_DEPENDS )
set(action_test_EXEC_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(action_test_RUN_DEPENDS "message_runtime" "roscpp" "std_msgs")
set(action_test_TEST_DEPENDS )
set(action_test_DOC_DEPENDS )
set(action_test_URL_WEBSITE "")
set(action_test_URL_BUGTRACKER "")
set(action_test_URL_REPOSITORY "")
set(action_test_DEPRECATED "")