set(_CATKIN_CURRENT_PACKAGE "single_joint")
set(single_joint_VERSION "1.0.0")
set(single_joint_MAINTAINER " <TODO@email.com>")
set(single_joint_PACKAGE_FORMAT "2")
set(single_joint_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(single_joint_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(single_joint_BUILDTOOL_DEPENDS "catkin")
set(single_joint_BUILDTOOL_EXPORT_DEPENDS )
set(single_joint_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(single_joint_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(single_joint_TEST_DEPENDS )
set(single_joint_DOC_DEPENDS )
set(single_joint_URL_WEBSITE "")
set(single_joint_URL_BUGTRACKER "")
set(single_joint_URL_REPOSITORY "")
set(single_joint_DEPRECATED "")