(cl:defpackage armc_visual-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "VISUALVAR"
   "<VISUALVAR-REQUEST>"
   "VISUALVAR-REQUEST"
   "<VISUALVAR-RESPONSE>"
   "VISUALVAR-RESPONSE"
  ))

