set(kinematics_SETUP_PY_VERSION "0.0.0")
set(kinematics_SETUP_PY_SCRIPTS "")
set(kinematics_SETUP_PY_PACKAGES "kinematics")
set(kinematics_SETUP_PY_PACKAGE_DIRS "src/kinematics")
set(kinematics_SETUP_PY_MODULES "")
set(kinematics_SETUP_PY_MODULE_DIRS "")