set(_CATKIN_CURRENT_PACKAGE "one_dof_link_moveit")
set(one_dof_link_moveit_VERSION "0.3.0")
set(one_dof_link_moveit_MAINTAINER "cyt <qyz146006@163.com>")
set(one_dof_link_moveit_PACKAGE_FORMAT "1")
set(one_dof_link_moveit_BUILD_DEPENDS "one_dof_link")
set(one_dof_link_moveit_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "one_dof_link")
set(one_dof_link_moveit_BUILDTOOL_DEPENDS "catkin")
set(one_dof_link_moveit_BUILDTOOL_EXPORT_DEPENDS )
set(one_dof_link_moveit_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "one_dof_link")
set(one_dof_link_moveit_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "one_dof_link")
set(one_dof_link_moveit_TEST_DEPENDS )
set(one_dof_link_moveit_DOC_DEPENDS )
set(one_dof_link_moveit_URL_WEBSITE "http://moveit.ros.org/")
set(one_dof_link_moveit_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(one_dof_link_moveit_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(one_dof_link_moveit_DEPRECATED "")