// Generated by gencpp from file armc_visual/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ARMC_VISUAL_MESSAGE_ADDTWOINTS_H
#define ARMC_VISUAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <armc_visual/AddTwoIntsRequest.h>
#include <armc_visual/AddTwoIntsResponse.h>


namespace armc_visual
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace armc_visual


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armc_visual::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::armc_visual::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::armc_visual::AddTwoInts > {
  static const char* value()
  {
    return "armc_visual/AddTwoInts";
  }

  static const char* value(const ::armc_visual::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::armc_visual::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::armc_visual::AddTwoInts > 
template<>
struct MD5Sum< ::armc_visual::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armc_visual::AddTwoInts >::value();
  }
  static const char* value(const ::armc_visual::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armc_visual::AddTwoIntsRequest> should match 
// service_traits::DataType< ::armc_visual::AddTwoInts > 
template<>
struct DataType< ::armc_visual::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::armc_visual::AddTwoInts >::value();
  }
  static const char* value(const ::armc_visual::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armc_visual::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::armc_visual::AddTwoInts > 
template<>
struct MD5Sum< ::armc_visual::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armc_visual::AddTwoInts >::value();
  }
  static const char* value(const ::armc_visual::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armc_visual::AddTwoIntsResponse> should match 
// service_traits::DataType< ::armc_visual::AddTwoInts > 
template<>
struct DataType< ::armc_visual::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::armc_visual::AddTwoInts >::value();
  }
  static const char* value(const ::armc_visual::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMC_VISUAL_MESSAGE_ADDTWOINTS_H
