// Generated by gencpp from file armc_visual/VisualVarRequest.msg
// DO NOT EDIT!


#ifndef ARMC_VISUAL_MESSAGE_VISUALVARREQUEST_H
#define ARMC_VISUAL_MESSAGE_VISUALVARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armc_visual
{
template <class ContainerAllocator>
struct VisualVarRequest_
{
  typedef VisualVarRequest_<ContainerAllocator> Type;

  VisualVarRequest_()
    : a(0)  {
    }
  VisualVarRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::armc_visual::VisualVarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armc_visual::VisualVarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VisualVarRequest_

typedef ::armc_visual::VisualVarRequest_<std::allocator<void> > VisualVarRequest;

typedef boost::shared_ptr< ::armc_visual::VisualVarRequest > VisualVarRequestPtr;
typedef boost::shared_ptr< ::armc_visual::VisualVarRequest const> VisualVarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armc_visual::VisualVarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armc_visual::VisualVarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace armc_visual

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armc_visual::VisualVarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armc_visual::VisualVarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armc_visual::VisualVarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::armc_visual::VisualVarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armc_visual/VisualVarRequest";
  }

  static const char* value(const ::armc_visual::VisualVarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n\
";
  }

  static const char* value(const ::armc_visual::VisualVarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualVarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armc_visual::VisualVarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armc_visual::VisualVarRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMC_VISUAL_MESSAGE_VISUALVARREQUEST_H
